checkly/checkly-cli

- README.md
Added an initial "Getting Started" section to the README as well as removed the emojis from the section headers.
> chore: initial getting-started README section

- src/commands/login.js
- src/services/login-util.js
Fixed the pkce implementation in our auhtorization code flow.
> fix: pkce state verification

- SECURITY.md
Add security.md for disclosing potential security vulns.
What do you think  @ianaya89 ? Obviously we can tweak the copy however you like :+1:
> feat: create security.md

- src/commands/logout.js
- src/services/config.js
- Add new public commands: `--help`, `--version` and `version`
- Update logout command to use latest config methods
> Add new public commands and fix logout

- src/commands/switch.js
Consider the scenario where a user with a single account tries to switch
> feat: add use case for single account users (switch)

- package-lock.json
- package.json
Reverts checkly/checkly-cli#94
> "chore(deps): bump ora from 5.4.1 to 6.0.1 [revert]"

- src/commands/init.js
Small copy update based on #110.
The example check can be `example-browser.yml` or `example-api.yml` depending on what the user chose, so I made the message a bit more generic and just said `..check out the example in this folder:`, more or less.
Sorry, this is the last thing I'm doing on vacation haha. Just came across @brampling's quick fix issue and couldn't resist :sweat_smile:
Fixes #110
> fix: init cmd copy [gh-110]

- sdk/index.js
- src/services/utils.js
Add the new sync query param to use it
> feat: use new sync methods

- package-lock.json
- src/commands/init.js
- src/commands/login.js
- src/parser/check-parser.js
- src/services/rollup-plugin-checkly-whitelist.js
- src/services/validator.js
> fix: eslint fix, use npm 6 for package lock and group schema

- sdk/index.js
- src/parser/check-parser.js
Pass groupId to the BE with a { ref: "<logicalId>" } object. This will allow us to have a distinction between existing resources of a user and project resource mappngs
> feat: pass groupId as ref to the BE [sh-0]

- .github/workflows/test.yml
Add actions for groups, in addition to individual checks, to smoke-test GH Action.
1. Create Group + Check
2. Update Group
3. Delete Group
> feat: test CRUD group actions [gh-00]

- .github/workflows/release.yml
Creates a new release for every commit. We can change this later on to the github releases
> chore: release when PR is merged to main

- package-lock.json
- package.json
- src/parser/bundler.js
- src/services/rollup-plugin-checkly-whitelist.js
Part of the PR from Nacho fix addresses the inline scripts
> fix: catch dependencies that we are not supported

- src/commands/deploy.js
- src/services/utils.js
> refactor: remove unnecessary function and clean up file

- src/commands/run.js
Allow users to pass where they wanna run their checks and remove fixed runtimeId
> feat: add a location flag to the check run

- src/templates/browser.js
Delete the title as it is not used
> fix: remove title from templates as it is not used

- src/modules/check-statuses/info.js
Shows the right test when the status is healthy
Fixes #111
> fix: print passing when the status is healthy

- sdk/index.js
- src/modules/checks/list.js
- test/commands/checks.spec.js
Parses the content-range header to figure out if there are more checks to fetch. We can also use this code for other resources that are shareable
> fix: fetch all the available checks

- package.json
> feat: release to npm upon merge

- src/commands/projects.js
- src/modules/projects/create.js
- src/modules/projects/index.js
This is quite useful for testing the cli features locally
> feat: allows the user to create projects

- .github/workflows/test.yml
Update secrets used in testing to login.
> fix: update login secrets

- package-lock.json
- package/package.json
- package/src/services/check-runner.ts
Closes https://github.com/checkly/checkly-cli/issues/361
> chore: run checks with max concurrency

- README.md
> docs: fixes typos and errors

- .github/workflows/test.yml
- package/e2e/__tests__/deploy.spec.ts
- package/e2e/__tests__/fixtures/check-parse-error/checkly.config.js
- package/e2e/__tests__/fixtures/check-parse-error/main.check.js
- package/e2e/__tests__/fixtures/check-parse-error/package.json
- package/e2e/__tests__/fixtures/deploy-project/checkly.config.ts
- package/e2e/config/default.js
- package/e2e/run-checkly.ts
- package/src/rest/projects.ts
Closes https://github.com/checkly/checkly-cli/issues/313
* Add the e2e test to the PR check GitHub Action
* Make sure that resources are cleaned up for `deploy.spec.ts`
* Fix the project structure for `check-parse-error.spec.ts`
> chore: add e2e tests in PR check

- README.md
- package/src/constructs/browser-check.ts
- package/src/constructs/check-group.ts
Add relative path support to checks and check group pattern
> feat: add relative path support to check and check groups [sc-0]

- package-lock.json
- package/package.json
- package/src/services/check-runner.ts
This PR reverts 90fcd4a23b41dc96ae70222082b250954d0ac6fa to re-introduce the check run queue. Limiting the number of concurrent check runs is a temporary workaround for https://github.com/checkly/checkly-cli/issues/400.
> chore: re-introduce check concurrency limit

- package-lock.json
- package/package.json
Lets make a new release with the OAuth fix (https://github.com/checkly/checkly-cli/pull/403).
> chore: release new version

- package/src/constructs/check-group.ts
- package/src/constructs/check.ts
Support private locations in the constructs
Closes https://github.com/checkly/checkly-cli/issues/386
> feat: support private locations with slugname [sc-0]

- README.md
- Correct some typos, missing words and spelling errors in the README file.
> fix: correct spelling in readme.md [sc-0]

- package-lock.json
- package/package.json
- package/src/commands/test.ts
* Update oclif deps
* Migrate to the new arg definition
Closes https://github.com/checkly/checkly-cli/issues/448
> chore: update oclif deps [sc-0]

- package/src/constructs/browser-check.ts
- package/src/services/check-parser/__tests__/check-parser.spec.ts
- package/src/services/check-parser/collector.ts
- package/src/services/check-parser/parser.ts
Reuse the content from Parser instead of reading stuff in the constructors one more time
> chore: reuse file content from the collector [sc-0]

- package/src/commands/whoami.ts
- package/src/rest/api.ts
- package/src/rest/users.ts
Resolves https://github.com/checkly/checkly-cli/issues/425
- Add logged in user name to the `whoami`
> feat: add logged in user to whoami response [sc-0]

- package/package.json
> chore: create a new release

- packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/simple-example/entrypoint.js
- packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/simple-example/module-package/main.js
- packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/simple-example/module-package/package.json
- packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/simple-example/module/index.js
- packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/typescript-example/entrypoint.ts
- packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/typescript-example/module-package/main.js
- packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/typescript-example/module-package/package.json
- packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/typescript-example/module/index.ts
- packages/cli/src/services/check-parser/__tests__/check-parser.spec.ts
- packages/cli/src/services/check-parser/parser.ts
Support barrel files for TS and JS
> feat: support barrel files for ts and js [sc-0]

- package-lock.json
- packages/cli/package.json
> feat: release 0.3.12 [sc-0]

- .github/workflows/release.yml
Fix a small bug in the new package structure
> fix: update readme copy with the correct paths [sc-0]

- packages/cli/src/commands/test.ts
- packages/cli/src/reporters/abstract-list.ts
- packages/cli/src/reporters/ci.ts
- packages/cli/src/reporters/list.ts
- packages/cli/src/services/check-runner.ts
Add a verbose flag so it is easier to debug code
> Resolves https://github.com/checkly/checkly-cli/issues/490
> feat: add verbose flag to show logs without failures [sc-0]

- package-lock.json
- packages/cli/package.json
> feat: release 0.3.14 [sc-0]

- README.md
- packages/cli/src/commands/runtimes.ts
- packages/cli/src/constructs/check-group.ts
- packages/cli/src/constructs/check.ts
- Add new `npx checkly runtimes` command, which lists all the available runtimes and their dependencies
- Add new `Region` type and JSdoc descriptions to restrict the `locations` values
- Add new `runtimes` command to the README.
> Resolves #492
> feat: add runtimes command [sc-0]

- examples/advanced-project/src/services/api/api.check.ts
- examples/boilerplate-project/__checks__/api.check.ts
- packages/cli/src/constructs/construct.ts
- packages/cli/src/constructs/project.ts
- Add `logicalId` validation.
- Now the `Project` construct class extends from `Construct`
> Resolves #487
- Important: we have to confirm all Production/Staging projects compliant with the new `logicalId` format restriction.
> feat: add logicalId validation [sc-0]

- packages/cli/src/constructs/project.ts
- packages/cli/src/services/__tests__/checkly-config-loader.spec.ts
- packages/cli/src/services/__tests__/fixtures/configs/no-export-config.js
- packages/cli/src/services/__tests__/fixtures/configs/no-logical-id-config.js
- packages/cli/src/services/checkly-config-loader.ts
- packages/cli/src/services/project-parser.ts
* Make repoUrl optional as it is not required and didn't want to add validation
* Add projectName and logicalId validations to the config
> Resolves #[498]
> fix: handle missing or empty config exports [sc-0]

- README.md
- packages/cli/e2e/__tests__/deploy.spec.ts
- packages/cli/e2e/__tests__/fixtures/test-only-project/checkly.config.ts
- packages/cli/e2e/__tests__/fixtures/test-only-project/checks.check.ts
- packages/cli/e2e/__tests__/test.spec.ts
- packages/cli/src/commands/deploy.ts
- packages/cli/src/constructs/check.ts
- packages/cli/src/constructs/project.ts
- add `testOnly` (default: `false`) in `Check` construct to discard the check on `deploy` command
- prepare `synthesizeRecord()` to easily add `testOnly` flag into other resources/construts, if we require this in the future
- include `testOnly` flag in docs
> Resolves #510
> feat: add testOnly flag for checks [sc-0]

- package-lock.json
- packages/cli/package.json
The examples currently use `AssertionBuilder` but it isn't released yet. This PR prepares a release of `@checkly/cli` so that `AssertionBuilder` is released and the examples are again usable by users.
> release version 0.3.15 of @checkly/cli

- examples/advanced-project/package.json
- packages/cli/src/constructs/check-group.ts
- packages/cli/src/constructs/check.ts
- packages/cli/src/services/checkly-config-loader.ts
- packages/create-cli/package.json
> Tnolet comment copy tweaks

- .github/workflows/release.yml
> chore: update slack channel for CI

- packages/cli/src/services/check-parser/errors.ts
- detect CLI construct usage in spec file and returns a detailed error message.
> Resolves #387
> feat: detect construct usage in spec file [sc-0]

- package-lock.json
- packages/cli/package.json
* Update luxon to address a CVE
* Cut the beta release
> feat: release 0.4.0 for the beta phase [sc-0]

- packages/cli/src/constructs/check-group.ts
Adds doubleCheck prop to the groups. There is a BE PR associated with this as well
> Resolves #[536]
> feat: add doubleCheck support for groups [sc-0]

- package-lock.json
- packages/cli/package.json
> feat: release 0.4.1 [sc-0]

- package-lock.json
- packages/cli/package.json
> feat: release v0.4.2

- package-lock.json
- packages/cli/package.json
Having the changes to `--preview` (https://github.com/checkly/checkly-cli/pull/542) would be useful for the launch week demo.
> feat: release @checkly/cli v0.4.3

- package-lock.json
- packages/cli/package.json
Prepare for a release of v0.4.4 of `@checkly/cli`. The release should be made right after merging https://github.com/checkly/checkly-cli/pull/547. This will keep the examples in sync with `@checkly/cli` for users creating new example projects via `npm create @checkly/cli`.
> feat: release @checkly/cli v0.4.4

- README.md
> docs: update readme with beta mention

- .github/ISSUE_TEMPLATE/story.yml
- remove project/milestone reference from GH story template
> chore: remove project/milestone from story template [sc-0]

- examples/advanced-project/package.json
- examples/boilerplate-project/package.json
- move `@checkly/cli` package from `dependencies` to `devDependencies`
> chore: move checkly package to devDependencies [sc-0]

- package-lock.json
- packages/cli/package.json
Windows users are currently affected by https://github.com/checkly/checkly-cli/issues/551. We can do a release so that the fix is available.
> feat: release version 0.4.5 of CLI

- package-lock.json
- packages/cli/package.json
Windows users are currently affected by #568 and #572. We can do a release so that the fix is available.
> feat: release version 0.4.6 of CLI

- .gitignore
- packages/cli/e2e/__tests__/deploy.spec.ts
- packages/cli/package.json
- packages/cli/src/commands/destroy.ts
- packages/cli/src/commands/runtimes.ts
- packages/cli/src/rest/projects.ts
- packages/cli/tsconfig.json
* Implement a destroy command delete projects
* Remove the only dot in the command descriptions
* Add the ts watch command to the package.json for development
We need to wait until we deploy the new BE to merge this
Resolves #565
> feat: add the destroy command [sc-0]

- package-lock.json
- packages/cli/package.json
> feat: release v0.4.7 [sc-0]

- packages/cli/src/services/checkly-config-loader.ts
- add `privateLocations` property into the default checks configuration.
> Resolves #576
> feat: add privateLocations to checks default config [gh-576]

- packages/cli/src/commands/login.ts
> refactor: clarify “existing session” prompt when logging in

- packages/cli/e2e/__tests__/destroy.spec.ts
- packages/cli/src/commands/destroy.ts
- add `-f` / `--force` flag for `destroy` command
- add E2E test cases for `destroy` command.
Reminder: add new flag into the CLI docs.
> feat: add --force flag to destroy command [gh-0]

- examples/advanced-project/src/services/docs/__checks__/docs-search.spec.ts
We recently updated the title for checklyhq.com/docs, breaking the example PW test. This PR updates the assertion to get the example working again.
> fix: update assertion in advanced example

- packages/cli/src/auth/index.ts
- packages/cli/src/commands/login.ts
Change login flow so a prompt for either logging in or signing up is presented to the user:
> feat: allow choosing auth mode when logging in

- packages/cli/src/commands/deploy.ts
- packages/cli/src/reporters/abstract-list.ts
- packages/cli/src/reporters/dot.ts
- packages/cli/src/reporters/list.ts
Don't use require to import chalk
> chore: use the import syntax for chalk [sc-0]

- package-lock.json
- packages/cli/package.json
> feat: release CLI v0.4.10

- package-lock.json
- packages/cli/package.json
- packages/cli/src/services/check-runner.ts
Set the timeouts before we hit the run session command. It is async so we might get the check run result before the test session rest call ends
> fix: set timeouts before the run command [gh-0]

- packages/cli/e2e/__tests__/help.spec.ts
- packages/cli/package.json
- packages/cli/src/auth/index.ts
- packages/cli/src/commands/deploy.ts
- packages/cli/src/commands/destroy.ts
- packages/cli/src/commands/login.ts
- packages/cli/src/commands/logout.ts
- packages/cli/src/commands/runtimes.ts
- packages/cli/src/commands/switch.ts
- packages/cli/src/commands/test.ts
- packages/cli/src/commands/whoami.ts
- packages/cli/src/constructs/api-check.ts
- packages/cli/src/constructs/browser-check.ts
- packages/cli/src/constructs/project.ts
- packages/cli/src/help/examples.ts
- packages/cli/src/help/help-extension.ts
- packages/cli/src/messages/common-messages.ts
- packages/cli/src/rest/api.ts
- packages/cli/src/services/check-parser/parser.ts
- packages/cli/src/services/util.ts
- full review of common messages and help text
- extends help command to show Examples section.
> Resolves [#555]
> 555 story review error messages

- examples/advanced-project/checkly.config.ts
- examples/boilerplate-project/checkly.config.ts
- packages/cli/src/commands/test.ts
- packages/cli/src/reporters/dot.ts
- packages/cli/src/reporters/reporter.ts
- packages/cli/src/reporters/util.ts
- packages/cli/src/services/checkly-config-loader.ts
- add `reporters` configuration property within the `cli` object, into the config file.
> Resolves #635
> feat: add multiple reporters config [gh-635]

- .github/dependabot.yml
* This is supposed to fix dependabot with workspaces
> fix: set versioning strategy to fix dependabot [sc-0]

- packages/cli/e2e/__tests__/deploy.spec.ts
- packages/cli/e2e/__tests__/destroy.spec.ts
* Use a new project logical id for each test
* Increase duration to 20s
* Delete directly the project instead of fetching it if the project logical id is passed
> chore: improve deploy job [sc-0]

- package-lock.json
- packages/cli/package.json
> feat: release version 0.4.13 of CLI

- CONTRIBUTING.md
- README.md
- examples/advanced-project/README.md
- examples/advanced-project/checkly.config.ts
- examples/advanced-project/package.json
- examples/advanced-project/src/__checks__/api.check.ts
- examples/advanced-project/src/__checks__/home.check.ts
- examples/advanced-project/src/__checks__/website.check-group.ts
- examples/advanced-project/src/alert-channels.ts
- examples/advanced-project/src/services/api/__checks__/api.check.ts
- examples/boilerplate-project/README.md
- examples/boilerplate-project/__checks__/api.check.ts
- examples/boilerplate-project/package.json
- package-lock.json
- packages/create-cli/package.json
- packages/create-cli/src/actions/dependencies.ts
- packages/create-cli/src/utils/messages.ts
> Relates to #566
We now have [checkly](https://www.npmjs.com/package/checkly) and [create-checkly](https://www.npmjs.com/package/checkly) packages on NPM. This PR updates the examples and README's to use the new packages.
> feat: update references to @checkly/cli package

- .github/workflows/release-canary.yml
We recently moved the CLI NPM package from `@checkly/cli` to `checkly`. This PR also updates the canary release process accordingly.
> chore: update the canary release package name

- CONTRIBUTING.md
We recently added a GitHub action for releasing the create-checkly package (https://github.com/checkly/checkly-cli/pull/666). This PR adds some documentation to CONTRIBUTING.md.
> docs: docoument create-checkly release process

- packages/cli/src/reporters/__tests__/__snapshots__/github-md-builder.spec.ts.snap
- packages/cli/src/rest/api.ts
- packages/cli/src/services/config.ts
- packages/cli/src/services/socket-client.ts
This PR is not yet supporting full local development. There will be further work for auth0 related work which will come later on
* Change NODE_ENV to CHECKLY_ENV given NODE_ENV can overlap with other packages
* Move api url to the config as well
> chore: rename env var and move api url to the config [gh-0]

- package-lock.json
- packages/cli/package.json
> feat: release CLI v4.0.4

- package-lock.json
- packages/create-cli/package.json
Release new version for create-cli
> feat: release create-cli v0.0.4

- packages/cli/src/services/test-runner.ts
Send file path to the BE as well
> feat: send file path to the BE [gh-0]

- package-lock.json
- packages/cli/package.json
> feat: release version 4.0.6 [gh-0]

- packages/cli/e2e/__tests__/switch.spec.ts
- packages/cli/e2e/run-checkly.ts
- packages/cli/src/commands/switch.ts
Fix the `switch` command. This is a regression after the migration from `inquirer` to `prompts` https://github.com/checkly/checkly-cli/pull/720
Add new `test:e2e` an async approach to be able to test prompts. (TODO: refactor it and make it nicer).
> Resolves #726
> fix: switch command [gh-726]

- package-lock.json
- packages/cli/package.json
- packages/cli/src/commands/login.ts
* Use select type to instead of list
* Pass a value as well to abide prompts api
> Resolves #732
> fix: use the write input type for account names [gh-732]

- packages/cli/e2e/__tests__/help.spec.ts
- packages/cli/e2e/command-matchers.ts
- packages/cli/src/commands/trigger.ts
There are no functional changes. I only made the help overview consistent.
> chore: update help messages

- CONTRIBUTING.md
- packages/cli/package.json
- packages/cli/src/services/config.ts
* remove the test env and just keep staging
* add development env and rename the former development to local
> feat: add development env and remove test env [gh-0]

- packages/cli/src/commands/login.ts
Modify the default login option to "open the browser".
> Resolves #740
> chore: open browser for login as default [gh-740]

- packages/cli/src/constructs/dashboard.ts
- packages/cli/src/constructs/maintenance-window.ts
- added links to docs in the constructor JSDocs
- some typos removal
- some small clarifications
> docs: tweaks to dashes and maintenance window jsdocs [sc-00]

- package-lock.json
- packages/cli/package.json
Release v4.0.9 of the CLI.
Tested the advanced and boilerplate examples with `npx checkly test` and `npx checkly deploy`.
The changes since v4.0.8 is https://github.com/checkly/checkly-cli/compare/v4.0.8...chris-lample/release-4-0-9
> feat: release CLI v4.0.9

- packages/cli/e2e/__tests__/deploy.spec.ts
- packages/cli/e2e/__tests__/fixtures/deploy-esm-project/api.check.mjs
- packages/cli/e2e/__tests__/fixtures/deploy-project/api.check.ts
- packages/cli/e2e/__tests__/fixtures/deploy-project/private-location.check.ts
- packages/cli/e2e/__tests__/fixtures/test-duplicated-groups/group2.check.ts
- packages/cli/src/commands/deploy.ts
- packages/cli/src/rest/projects.ts
- packages/cli/src/services/__tests__/project-parser-fixtures/simple-project/src/services/search-service.check.js
Allow users to disable schedule on deploy
> Resolves (after release) #779
> feat: allow users to disable schedule on deploy [gh-779]

- package-lock.json
- packages/cli/package.json
- packages/cli/src/rest/api.ts
Adds proper proxy support to the cli
> feat: add proxy support to the cli [gh-0]

- package-lock.json
- packages/cli/package.json
- packages/cli/src/auth/index.ts
- packages/cli/src/services/socket-client.ts
- packages/cli/src/services/util.ts
* Change the library for the proxy
* Add the last missing proxy axios
* Add proxy support to the mqtt client
> fix: use the http tunnel proxy [sc-0]

- packages/cli/src/services/checkly-config-loader.ts
This PR adds `retryStrategy` to the allowed values in checkly config defaults.
> feat: add retryStrategy to checkly config defaults

- examples/advanced-project-js/src/__checks__/heartbeat.check.js
- examples/advanced-project/src/__checks__/heartbeat.check.ts
- examples/boilerplate-project-js/__checks__/heartbeat.check.js
- examples/boilerplate-project/__checks__/heartbeat.check.ts
Adjusting examples to reduce default frequency.
> feat: adjust default grace and period for heartbeat checks [sc-17531]

- examples/advanced-project-js/checkly.config.js
- examples/advanced-project-js/src/__checks__/website-group.check.js
- examples/advanced-project/checkly.config.ts
- examples/advanced-project/src/__checks__/website-group.check.ts
- packages/cli/src/constructs/retry-strategy.ts
Rename maxAttempts to maxRetries
> refactor: rename maxAttempts to maxRetries [gh-0]

- packages/cli/src/constructs/retry-strategy.ts
We previously decided that `sameRegion` for retry strategies should default to `true`.
> feat: update sameRegion default to true

- commitlint.config.js
- We decided to not require issue references in all commit messages, as long as they're in the PR title so that shortcut can link the PR correctly. (See: https://checklyhq.slack.com/archives/CSG0W8UTG/p1697700201010529)
- However, our `commitlint` rules still required them, this PR removes that commitlint rule
> fix: rm commitlint issue ref setting [sc-00]

- examples/advanced-project-js/src/__checks__/spacex-requests.spec.js
- examples/advanced-project/src/__checks__/spacex-requests.spec.ts
Move assertions to be inside of the `test.step`
> feat(multistep): update template best practice [sc-00]

- packages/cli/src/services/util.ts
`walkDirectory` isn't used at all. This PR removes it to keep the codebase clean.
> refactor: remove unused method

- packages/cli/src/commands/deploy.ts
- packages/cli/src/commands/test.ts
Enable snapshot support by default for test and the deploy flows
> feat: enable the default snapshot support [gh-0]

- packages/cli/src/commands/test.ts
The check only provides groupId information, hence the part of trying to get the group from the check ref
> Resolves #878
> feat: add ability to filter by group tag

- packages/cli/src/constructs/browser-defaults.ts
Add support for `accuracy`, `toHaveScreenshot` and `toMatchSnapshot` on playwright config
> feat: add missing options on playwright config support

- packages/cli/src/constructs/check.ts
> chore: update check `activated` field jsdoc hint

- examples/advanced-project-js/checkly.config.js
- examples/advanced-project-js/src/__checks__/multi-step-spacex.check.js
- examples/advanced-project/checkly.config.ts
Examples where using wrong urls + imports
> fix: examples not working

- examples/advanced-project-js/src/__checks__/api.check.js
- examples/advanced-project-js/src/__checks__/home.check.js
- examples/advanced-project-js/src/__checks__/multi-step-spacex.check.js
- examples/advanced-project-js/src/__checks__/website-group.check.js
- examples/advanced-project/src/__checks__/api.check.ts
- examples/advanced-project/src/__checks__/home.check.ts
- examples/advanced-project/src/__checks__/multi-step-spacex.check.ts
- examples/advanced-project/src/__checks__/website-group.check.ts
- examples/boilerplate-project-js/__checks__/api.check.js
- examples/boilerplate-project/__checks__/api.check.ts
Set examples to use `runParallel: true` by default
> feat: examples set runParallel:true [sc-00]

- packages/cli/src/constructs/playwright-config.ts
- packages/cli/src/playwright/playwright-config-template.ts
- packages/create-cli/src/utils/playwright-config-template.ts
Add support for userAgent in playwright config
> feat: support userAgent playwright config

- CONTRIBUTING.md
> docs: clarify prerelease testing

- packages/cli/src/commands/test.ts
Run multistep test with filepath argument
> fix: multistep test with fileargs [sc-00]

- packages/cli/src/services/socket-client.ts
> Resolves #[949](https://github.com/checkly/checkly-cli/issues/949)
Retry + backoff mechanism when trying to connect
> feat: add retry mechanism to socket connect

- package-lock.json
- packages/cli/package.json
- packages/create-cli/package.json
Bump axios version to 1.7.4 for a security update
Resolves #957
> chore: bump axios version to 1.7.4

- examples/advanced-project-js/src/__checks__/homepage.spec.js
- examples/advanced-project-js/src/__checks__/login.spec.js
- examples/advanced-project/src/__checks__/homepage.spec.ts
- examples/advanced-project/src/__checks__/login.spec.ts
Update checkly examples to use only the baseURL
> chore: use baseURL [sc-0]

- packages/cli/src/services/socket-client.ts
- packages/cli/src/services/util.ts
This PR fixes the issue of constructing proxy Auth object while creating the tunnel agent.
> Resolves #967
> bug: Fix proxy auth assignment while creating tunnel agent

- examples/advanced-project-js/checkly.config.js
- examples/advanced-project/checkly.config.ts
- examples/boilerplate-project-js/checkly.config.js
- examples/boilerplate-project/checkly.config.ts
> docs: fix doc URL

- packages/cli/src/constructs/tcp-check.ts
> fix: fix wrong reference URL for TcpCheck construct [sc-23083]

- packages/cli/src/reporters/abstract-list.ts
- `white.dim` is hard to read on some terminals. Move to just `white`
> feat: changes color or tip to be easier to read

- .github/workflows/release-canary.yml
Allow custom label for canary releases
> feat: modify workflow to allow custom tagging

- packages/cli/src/constructs/playwright-check.ts
Add the missing assignments to playwright checks
> fix: add alert channel and pl assignments in playwright checks [sc-0]

- package-lock.json
Seems this was not done/detected in #1076.
> chore: update monorepo package lock file [sc-0]

- packages/cli/src/commands/import/plan.ts
This PR makes it possible to generate code for an import plan loaded from a file. The file must be in the same format as a normal import plan, and the `--debug-import-plan` option can be used to create a sample file from one's importable resources, like this:
```
npx checkly import plan --debug-import-plan --preview
```
Follow the dialog options and you'll end up with a `./debug-import-plan.json` file. Note: the `--preview` option makes sure that no actual import plan is created. If you do not use the preview option, you might want to cancel the import plan with the following command instead:
```
npx checkly import cancel
```
To generate code from the debug import plan file, call:
```
npx checkly import plan --debug-import-plan-input-file ./debug-import-plan.json
```
Since this …
> feat(internal): utility to generate code for an import plan loaded from a file [sc-24645]

- packages/cli/src/services/util.ts
This will allow us to have the correct permissions for all files in the code bundle `-rwxr-xr-x`
> fix: set correct permissions to all pw bundle files

- .github/workflows/release.yml
- .github/workflows/test.yml
A fully automated solution is not included, but this will at least make it easier to access the rules for a manual upload.
> chore: store LLM rules as artifacts on prerelease/release builds [sc-24849]

- packages/cli/src/commands/rules.ts
> feat: single select in interactive mode and printing the rules to stdout in non interactive mode

- packages/cli/src/commands/pw-test.ts
- packages/cli/src/services/check-parser/package-files/package-manager.ts
- packages/cli/src/services/checkly-config-loader.ts
- packages/cli/src/services/project-parser.ts
- packages/cli/src/services/util.ts
Minor fixes:
1. Make current dir root when resolving lock files for playwright checks
2. Allow using non-root directory for playwright config file
3. Allow using playwright's own `--config` flag when running `pw-test`
> chore: minor bug fixes/features for playwright checks

- packages/cli/src/services/abstract-check-runner.ts
Use custom timeout error for pw checks
> feat: use custom timeout error for pw checks

- packages/cli/src/constructs/project.ts
Add type of construct on validation error 
```
Parsing your project... !
Error: The "logicalId" of a check construct must be a string (logicalId=undefined [undefined])
```
> feat: add type of construct on validation error
