checkly/checkly-cli

sdk/index.js, src/commands/login.js, src/commands/whoami.js
Fix `accounts` module name in `whoami` and `login` commands.
=> Update accounts api module name

src/commands/init.js
This PR changes the order of some actions in the `init` command. Moving the creation of the project, and communication with the backend, to earlier in the process. 
This is so that in case of network or any other BE errors, the process exits earlier, and the users are not left with a dangling invalid `.checkly` directory.
The current order of operations is such that - first the `.checkly` directory gets created, as well as an example check. After that, we talk with the backend and create the project in the DB, get back an ID for it, etc. and write that to the `.checkly/settings.yml` file. If it were to fail at that …
=> fix(init): create project on BE before writing .checkly dir [gh-00]

src/commands/accounts.js, test/commands/accounts.spec.js
Remove `exit` from accounts command and fix output
> Resolves #139 139
=> fix: remove this.exit from accounts command

src/modules/projects/list.js
Only shows the formatted fields for the project endpoint
=> chore: only show the formatted fields

src/commands/run.js, src/parser/index.js
This is an idea on how `checkly-cli run` would work with logical ids we have in the repo
`checkly-cli run example-api.yml`. This is not the path but the logical ids what the parser returns. We can also change the command to something like `checkly-cli run .checkly/checks/example-api.yml`
=> feat: allow users to pass logical id to run checks

src/modules/add/check.js
Allow selecting a group when running `add check` command
> Resolves #113
=> feat: add group selection when creating checks

sdk/api/modules/checks.js, test/commands/checks.spec.js, test/commands/deploy.assertions.spec.js
Fix checks pagination sending limit & page params as query string
=> fix: send checks paginations params as qs

src/modules/checks/list.js, src/modules/groups/list.js, src/services/utils.js, test/bundler/bundler.spec.js, test/commands/checks.spec.js, test/commands/groups.spec.js
- Format check/groups locations when they have more than 3:
```
name       checkType  frequency  activated  locations
---------  ---------  ---------  ---------  ------------------------------------------------
001 Check  API        10         true       ap-northeast-2, ca-central-1, eu-west-1 + 4 more
002 Check  API        10         true       ap-northeast-2, ca-central-1, eu-west-1 + 2 more
```
> Resolves https://github.com/checkly/checkly-cli/issues/136
=> fix: format groups/check locations output

sdk/api/modules/projects.js, src/commands/link.js, src/modules/link/index.js, test/commands/help.spec.js
The `link` command allows users to link their local `checkly` directory with an existing project:
- The user can specify the target `projectId` as a command argument
- If the `projectId` is not set, the command will fetch the existing projects and prompt a list
> This command will only affect your local director (at least for now). It's only an interactive way to update project properties in the `global` settings file. Users will need to run `deploy` in order to impact changes in our DB state
> Resolves #153
=> feat: add link command

README.md, examples/simple-project/checkly.config.js, examples/simple-project/src/__checks__/simple.spec.js, package/src/commands/deploy.ts, package/src/commands/test.ts, package/src/services/checkly-config-loader.ts
Rename `checkMatch` for the `browser` block to `testMatch`
=> chore: rename checkMatch to testMatch [sc-0]

package/src/constructs/check.ts
A default value for `check.activated` is now set on the server side. We can safely remove this default value in the client.
=> chore: remove check.activated default

package/src/commands/deploy.ts
As suggested in https://github.com/checkly/checkly-cli/issues/372, it would be nice to let users now the name of the project that they're deploying to with `checkly deploy`. This avoids the need for them to run an extra `whoami` command.
This PR adds the logging with an extra call to the accounts API. 
```
$ npx checkly deploy
? You are about to deploy your project "Simple Project" to account "chris@checklyhq.com". Do you want to continue? Yes
Successfully deployed project "Simple Project" to account "chris@checklyhq.com".
```
Resolved #372
=> chore: include account information in deploy logs

README.md, package-lock.json, package/src/commands/test.ts, package/src/reporters/abstract-list.ts, package/src/reporters/ci.ts, package/src/reporters/list.ts, package/src/rest/api.ts, package/src/rest/private-locations.ts, package/src/services/check-runner.ts
Relates to https://github.com/checkly/checkly-cli/issues/352 and https://github.com/checkly/checkly-cli/issues/386
This PR adds support for running checks on private locations for `checkly test`. The PR adds a `--private-location` flag that can be used to pass the slug name of a private location.
Passing both `--location` and `--private-location`:
```
$ npx checkly test --location eu-central-1 --private-location test
›   Error: The following error occurred:
›     --location=eu-central-1 cannot also be provided when using --private-location
›   See more help with --help
```
Passing an invalid private location (gives …
=> feat: support checkly test on private locations

README.md, package/src/commands/test.ts, package/src/services/check-runner.ts, package/src/services/checkly-config-loader.ts
Closes https://github.com/checkly/checkly-cli/issues/352
This PR adds support for `cli.runLocation` and `cli.privateRunLocation` in the checkly config file. These default locations will then be used for `checkly test` runs.
=> feat: allow setting default run locations in checkly config

package/src/rest/api.ts
We don't actually use the `apiVersion` field. I think that it's not so useful and that we should just remove it.
=> chore: remove unused API path config

package/package.json, package/src/hooks/configure-api-client.ts, package/src/rest/api.ts
Knowing which agents are in-use could be helpful for making product decisions. This PR adds a `x-checkly-cli-version` header which will be incldued on requests to the Checkly backend.
=> chore: report cli version in http headers

package/src/auth/index.ts
Currently logging in with `npx checkly login` and using GitHub OAuth fails. After logging in with GitHub, the webpage redirects to the error page shown above. The reason is that the initial `/authorize` request to Auth0 goes to `checkly.eu.auth0.com`, but the `/callback` call to Auth0 goes to `auth.checklyhq.com`. This setup isn't supported by Auth0 - both requests are required to same domain ([relevant forum post](https://community.auth0.com/t/you-may-have-pressed-the-back-button-but-i-really-didnt/23877/16)). 
To fix the issue, we can just use the `auth.checklyhq.com` domain. This is the one that's already used when …
=> fix: use Checkly auth0 domain

README.md
Just fixed 2 typos.
Fixing 2 typos in the README.md
=> fix: 2 typos in README.md

package/src/services/project-parser.ts
Dont assign base defaults to browser check default. When a user sets a runtime in checkDefaults and leave it empty in browserCheckDefaults, the default will still kick in here
=> fix: dont assign defaults to browser check default [sc-0]

package/src/services/__tests__/check-dependency-parser-fixtures/esmodules-example/dep1.js, package/src/services/__tests__/check-dependency-parser-fixtures/esmodules-example/dep2.js, package/src/services/__tests__/check-dependency-parser-fixtures/esmodules-example/dep3.js, package/src/services/__tests__/check-dependency-parser-fixtures/esmodules-example/entrypoint.js, package/src/services/__tests__/check-dependency-parser.spec.ts, package/src/services/check-dependency-parser.ts
Resolves https://github.com/checkly/checkly-cli/issues/426
This PR adds support for ES Modules `import`+`export` syntax. The backend already supports this since we run all check files (even JS files) through the TypeScript compiler, which then outputs commonJS. All that's needed is to detect dependencies which are imported with ES Modules in `check-dependency-parser`.
This will only generally work for runtimes >= 2022.10, since we don't always apply the TypeScript compiler. Testing on an older runtime gave the following error:
```
ERROR, 5:45:02 PM, Failed to compile check script: …
```
=> feat: add ES Modules support

README.md, package/src/commands/test.ts, package/src/reporters/ci.ts, package/src/reporters/list.ts
Adds a `--list` flag to `test` command to just show the checks in a project, without executing them. 
P.S. also fixes a typo
=> feat: adds --list flag

package/src/constructs/browser-check.ts, package/src/services/check-parser/__tests__/check-parser-fixtures/typescript-example/dep4.js, package/src/services/check-parser/__tests__/check-parser-fixtures/typescript-example/entrypoint.ts, package/src/services/check-parser/__tests__/check-parser.spec.ts, package/src/services/check-parser/collector.ts, package/src/services/check-parser/parser.ts
* Allow more flexible setup for different extensions
* Allow TS files to import JS files
* Inline parsing errors to remove top try/catch
Closes https://github.com/checkly/checkly-cli/issues/423
=> fix: allow ts files to import js [sc-0]

package/e2e/__tests__/test.spec.ts, package/e2e/run-checkly.ts, package/src/services/check-runner.ts
Resolves https://github.com/checkly/checkly-cli/issues/443
When no checks are detected, `checkly test` would hang indefinitely. This PR adds a fix and an integration test to make sure that there are no regressions.
=> fix: terminate  when no checks

package/src/services/check-parser/__tests__/check-parser-fixtures/typescript-example/entrypoint.ts, package/src/services/check-parser/__tests__/check-parser-fixtures/typescript-example/type.ts, package/src/services/check-parser/__tests__/check-parser.spec.ts, package/src/services/check-parser/parser.ts
Handle the import type syntax of typescript
Closes https://github.com/checkly/checkly-cli/issues/440
=> fix: handle import type statement [sc-0]

package/src/constructs/check-group.ts, package/src/constructs/check.ts
Resolves https://github.com/checkly/checkly-cli/issues/442
- Use an empty array `[]` when `environmentVariables` is nullish (`null` or `undefined`) in checks and check-groups.
=> fix: use empty array if environmentVariables is nullish [sc-0]

package-lock.json, package/package.json
Resolves https://github.com/checkly/checkly-cli/issues/456
With this PR, we introduce a warning when a new `@checkly/cli` version is available. I expect that we'll be releasing quite a few new versions in the upcoming months. To avoid annoying users with too many messages, the plugin is configured to only check for updates once every 30 days.
Example (bumping down the version in package.json for testing):
[@oclif/plugin-warn-if-update-available](https://github.com/oclif/plugin-warn-if-update-available)
=> feat: warn when new @checkly/cli version is available

packages/cli/e2e/__tests__/test.spec.ts
The `Should terminate when no checks are found` test is currently flaky. For example, [here](https://github.com/checkly/checkly-cli/pull/468) it failed on 1 out of 3 executions. After adding more logging, I saw that the failure is due to reaching the 5 second timeout.
As a quick fix, we can simply increase the timeout to the 10 second default. 
I'm not sure why the `checkly test does-not-exist.js` command is taking so long. Running locally, this integration test takes 1.7 seconds. I've also tried directly running `npx checkly test does-not-exist.js` which took 1.2s. In this case, I think that the normal command isn't …
=> chore: increase timeout for flaky e2e test

packages/cli/src/auth/index.ts
Resolves https://github.com/checkly/checkly-cli/issues/445
Running `npx checkly login` may fail if port 4242 is already in use. As a simple improvement, this PR gives a more clear error message in this case. If users continue running into this error, we can invest more effort into removing the error case altogether.
=> chore: provide better error message for EADDRINUSE

package-lock.json, packages/cli/package.json, packages/cli/src/services/check-parser/parser.ts
Keep typescript as an optinal dependency
=> fix: keep typescript as an optinal dependency [sc-0]

packages/cli/src/constructs/api-check.ts
Relates to https://github.com/checkly/checkly-cli/issues/472
We already have sensible defaults for API check values in the backend. These are added via Joi and the DB (in the case of `followRedirects`). This PR makes some fields optional - the defaults will be used in this case.
* `degradedResponseTime`: 10000 (higher than the one mentioned in the issue, but it's worth the consistency with the public API + TF)
* `maxResponseTime`: 20000
* `followRedirects`: true
* `skipSsl`: false
* `assertions`: []
=> feat: enable default values for API checks

packages/cli/src/constructs/check-group.ts
Relates to https://github.com/checkly/checkly-cli/issues/472
We already have sensible defaults for check groups in the backend - added in the level Joi and DB level. With this PR, users can more easily create check groups with the default values:
`activated`: true
`muted`: false
`runtimeId`: `null`. In this case the runtimeId from the account will be used as a fallback.
`tags`: `[]`
`concurrency`: 3. This field wasn't mentioned in the GH issue, but I think that it makes sense to enable the default here as well.
`environmentVariables`: `[]`
`apiCheckDefaults` and `browserCheckDefaults` can also be skipped. This default …
=> feat: enable default values for groups

README.md, packages/cli/src/commands/test.ts, packages/cli/src/reporters/util.ts, packages/cli/src/services/check-runner.ts
> Resolves https://github.com/checkly/checkly-cli/issues/463
Normally, the CLI should always receive all check results when `checkly test` is executed. Even if a user's checks hang, there should be a result sent back to the CLI. Still, there might be some edge cases which cause results to never be sent back to the CLI. A websocket update might fail to be pushed, for example. With the current implementation, `checkly test` would just hang indefinitely.
As an extra fallback, this PR adds a timeout for `checkly test`. This way, the command won't hang indefinitely and block users' CI if there are ever any issues.
Rather …
=> chore: add a timeout for check executions

README.md, packages/cli/src/services/project-parser.ts
> Resolves https://github.com/checkly/checkly-cli/issues/485
`testMatch` in the Checkly config file allows users to automatically create browser checks from Playwright files. Users might not want this behavior at all, though.
Currently we set a default value for `testMatch`, so it isn't possible to disable the flag. With the new [clreate-cli](https://github.com/checkly/checkly-cli/tree/main/packages/create-cli) scaffolding, though, having a default is less important. 
This PR removes the default value for `testMatch` so that users can completely disable the feature.
=> feat: make browser check testMatch optional

packages/cli/src/commands/deploy.ts, packages/cli/src/commands/test.ts, packages/cli/src/constructs/browser-check.ts, packages/cli/src/constructs/check.ts, packages/cli/src/constructs/construct.ts, packages/cli/src/constructs/project.ts, packages/cli/src/reporters/abstract-list.ts, packages/cli/src/services/check-runner.ts, packages/cli/src/services/project-parser.ts, packages/cli/src/services/test-filters.ts
Currently the `Project` tracks all of the `synthesize()` result of checks, groups, and alert channels rather than tracking the original construct. This means that after parsing the project, we only have access to the results of `synthesize()`.
This has worked OK so far, but it also has a few small issues. In particular, we need to put internal properties in the `synthesize()` result. These internal properties need to be removed later on in `checkly deploy`  before messaging the backend https://github.com/checkly/checkly-cli/blob/f2ab503c5997de1fa9b1f5565bd3872395e1b48e/packages/cli/src/commands/deploy.ts#L72-L82
In …
=> chore: call synthesize() later on

README.md
Updates the README to remove the misleading `name` property in the Slack Alert channel example.
See: https://checklyhq.slack.com/archives/C046VCZPBNH/p1676024249563939
=> fix: remove name property for slack alert channel example [sc-00]

packages/cli/e2e/__tests__/fixtures/test-project/checks.check.ts, packages/cli/e2e/__tests__/test.spec.ts, packages/cli/e2e/run-checkly.ts, packages/cli/src/commands/baseCommand.ts, packages/cli/src/commands/test.ts, packages/cli/src/services/checkly-config-loader.ts
* Handle the missing cli field in the config
* Add the verbose flag support to the config as well
* Update the test to use the verbose flag as well to avoid false negatives
Tested the cases manually using the advanced-project
=> fix: handle no cli option and push verbose config [sc-0]

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/docs_request.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/story.yml
It appears that labels aren't automatically being added to new issues when using the GH issue templates. This PR changes the syntax to follow [this doc](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) and changes the label names to match our current labels. I'm not sure that it's possible to test this without merging, but I think that it should fix auto-labeling.
=> chore: change GH issue template labels

examples/advanced-project/checkly.config.ts, examples/boilerplate-project/checkly.config.ts
Having type checking and Intellisense completion for the Checkly config is quite useful ([docs here](https://www.checklyhq.com/docs/cli/project-structure/#config-intellisense)). We should consider making this the suggested setup in the examples, so that users don't need to search for it in the docs.
(Good idea @stefanjudis 🥳  )
=> docs: use defineConfig in examples

packages/cli/src/commands/test.ts, packages/cli/src/config.ts, packages/cli/src/constructs/check-group.ts, packages/cli/src/constructs/check.ts, packages/cli/src/services/check-runner.ts, packages/cli/src/services/checkly-config-loader.ts
- add typed `runLocation` attribute
- allow user to augment the `Region` type with missing new locations, example:
```ts
import { defineConfig, type Region } from '@checkly/cli'
declare module '@checkly/cli' {
export interface Region {
'ar-east-1': string
'ar-central-1': string
'ar-west-1': string
}
}
export default defineConfig({
projectName: 'Advanced Example Project',
logicalId: 'advanced-example-project',
repoUrl: 'https://github.com/checkly/checkly-cli',
checks: {
locations: ['us-east-1', 'ar-central-1'],
tags: ['mac'],
runtimeId: '2022.10',
checkMatch: '**/*.check.ts',
browserChecks: {
testMatch: …
```
=> feat: allow Region type augmentation [sc-0]

packages/cli/src/constructs/check-group.ts, packages/cli/src/services/__tests__/util.spec.js, packages/cli/src/services/project-parser.ts, packages/cli/src/services/util.ts
> Resolves #539 
On Windows, the path separator is `\` rather than `/`. The relative path of `testMatch` files is used in the logical ID. This causes problems, though, since `\` isn't an allowed character in logical IDs. Users on Windows will receive the following error:
```
Error: The 'logicalId' must includes only allowed characters [A-Za-z0-9_-/#.]. (logicalId='src\__checks__\check.spec.ts')
```
Additionally, logical ID's should be consistent across platforms. If `npx checkly deploy` produces different logical IDs in Linux CI vs a Windows developer laptop, then users would constantly see checks being deleted and …
=> fix: handle Windows path separator for logical IDs

examples/advanced-project/package.json, examples/boilerplate-project/package.json, package-lock.json
Currently the examples are set to use version `^0.3.13` of `@checkly/cli`. Since there isn't yet a `1.0.0` release, though, this will enforce that the version `0.3.x` is used ([more info](https://michaelsoolee.com/npm-pre-1-caret-rules/)). Users of `npx create @checkly/cli` will end up using the alpha version `0.3.15` rather than the latest version of `@checkly/cli`.
One fix would simply be to update the exampels to use `^0.4.0`. I think that we may have trouble forgetting to keep this up-to-date, though, when `0.5.0` is released. To make sure that the examples are always using the latest CLI version, this PR simply …
=> feat: use latest checkly/cli version in examples

packages/cli/src/commands/authCommand.ts, packages/cli/src/commands/login.ts, packages/cli/src/rest/api.ts
> Resolves #545 
When there's no internet connection, the CLI fails with an unclear error. This can be reproduced by disabling WIFI.
```
$ npx checkly test
TypeError: Cannot destructure property 'status' of 'err.response' as it is undefined.
```
This PR detects this case by checking whether `err.response` is defined, and returns a more specific error message. The error messages returned are now: 
Incorrect API key (unchanged):
```
$ npx checkly test
Error: Authentication failed with Account ID "bf7babe3-0589-4cc9-9358-f706b3b11362"
and API key "...8b0f"
```
Wifi Disabled:
```
$ npx checkly test
Error: Encountered an …
```
=> fix: log clear error in case of internet connection issues

examples/advanced-project/src/__checks__/group.check.ts, packages/cli/e2e/__tests__/fixtures/test-duplicated-groups/group1.check.ts, packages/cli/e2e/__tests__/fixtures/test-duplicated-groups/group2.check.ts, packages/cli/src/constructs/__tests__/browser-check.spec.ts, packages/cli/src/constructs/check-group.ts, packages/cli/src/constructs/check.ts
The `Check` construct already accepts `alertChannels` as actual `AlertChannel` constructs, but for `groupId` it accepts a `Ref` rather than a `CheckGroup`. This is a bit inconsistent, and it would be nice to follow one pattern for linking constructs. 
https://github.com/checkly/checkly-cli/blob/d1a1bed14d68fba64103b916bc8f90fedbec37d3/packages/cli/src/constructs/check.ts#L62-L65
This PR updates the preferred method of assigning a check to a group from passing a ref:
```
new BrowserCheck('logicalId', { groupId: group.ref() })
```
to passing the group construct:
```
new BrowserCheck('logicalId', { group })
```
This is …
=> feat: allow setting check group without calling ref()

packages/cli/src/commands/deploy.ts
Currently `npx checkly deploy --preview` has no output at all when no checks or other resources are detected. This output could be a bit misleading for new users.
This PR adds some output for this case:
```
$ npx checkly deploy --preview
No checks were detected. More information on how to set up a Checkly CLI project is available at https://checklyhq.com/docs/cli/.
```
This issue could happen for a number of reasons, so I'm not sure if it makes sense to give any other info in the output for now.
=> feat: log error message when no resources in deploy preview

packages/cli/package.json, packages/cli/src/constructs/browser-check.ts, packages/create-cli/package.json
- fix browser checks dependencies path separator when executing `test` or `deploy` on Windows
- replace `rm -rf ./dist` with `rimfaf ./dist` allowing contributors running Windows
> Resolves #551
=> fix: dependencies path separator in Windows [sc-0]

packages/cli/src/constructs/api-check.ts, packages/cli/src/constructs/opsgenie-alert-channel.ts
* export BodyType and migrate it to a type
* turn opsgenie region and priority to types
=> fix: export BodyType and migrate enums to string literals [sc-0]

.github/workflows/test.yml, package-lock.json, packages/cli/e2e/__tests__/deploy.spec.ts, packages/cli/e2e/__tests__/test.spec.ts, packages/cli/e2e/run-checkly.ts, packages/cli/package.json, packages/cli/src/constructs/__tests__/browser-check.spec.ts, packages/cli/src/services/check-parser/__tests__/check-parser.spec.ts, packages/cli/src/services/check-parser/parser.ts
We seem to have a decent number of users on Windows. With this PR we'll also run the integration tests on Windows. That should help us avoid regressions.
If this PR is accepted, we should update the branch protection rules to match the new jobs.
[cross-env](https://www.npmjs.com/package/cross-env) is added as a dev dependency. This lets us set env vars for the integration tests in a cross platform way.
=> chore: add integration testing on Windows

CONTRIBUTING.md, packages/cli/package.json, packages/cli/src/commands/deploy.ts, packages/cli/src/constructs/api-check.ts, packages/cli/src/reporters/util.ts, packages/cli/src/rest/assets.ts, packages/cli/src/services/check-runner.ts, packages/cli/src/services/checkly-config-loader.ts, packages/cli/src/services/config.ts
We recently decided to prefer Union Types rather than Enums in publicly facing code. To make sure that we have a consistent code style, this PR adds an ESLint rule (from [here](https://github.com/typescript-eslint/typescript-eslint/issues/561#issuecomment-496664453)).
This PR also adds a small note in Contributing.md.
In cases where enums are already used, this PR just disables the lint rule.
=> chore: lint enum usage

packages/cli/e2e/__tests__/fixtures/test-project/src/__checks__/group.check.ts, packages/cli/src/constructs/browser-check.ts, packages/cli/src/constructs/check-group.ts, packages/cli/src/services/__tests__/util.spec.js, packages/cli/src/services/project-parser.ts, packages/cli/src/services/util.ts
- fix duplicated `logicalId` error converting all path to POSIX. This fixes the problem checking if the check was already added with `preexistingCheckFiles.has(relPath)`.
- add checks into the `test-project` for the E2E test.
- `checkFileAbsolutePath` is not modified/covered by this PR.
> Resolves #572
=> fix: transform all path to POSIX [sc-0]

examples/advanced-project/src/__checks__/404.spec.ts, examples/advanced-project/src/__checks__/homepage.spec.ts, examples/advanced-project/src/services/docs/__checks__/docs-search.spec.ts, examples/boilerplate-project/__checks__/homepage.spec.ts
If PWT is installed in the same project TS complains about our example code. This PR doesn't change functionality and only makes TS happy.
=> fix: clean up TS warnings if PWT types are available

package-lock.json, packages/cli/package.json
Currently the latest CLI release is out of sync with the examples. The latest CLI release expects `skipSsl`, but the examples use `skipSSL`. This causes an error for users going through the `npm create @checkly/checkly-cli` flow.
To resolve this, we can make a new release of the CLI.
=> feat: release CLI v0.4.9

packages/cli/package.json
Add `engines` property to CLI `package.json` to warn folks when they're using the wrong Node.js version
=> chore: add engines property to cli package.json

packages/cli/src/commands/whoami.ts
- Add `accountId` when running `whoami` command
```bash
> You are currently on account "nacho@checklyhq.com" (111ac7a7-466b-4d15-b07d-8b051626f754) as Ignacio Anaya.
```
=> chore: add account id to `whoami` output [sc-00]

packages/cli/src/reporters/__tests__/__snapshots__/util.spec.ts.snap, packages/cli/src/reporters/__tests__/fixtures/api-check-result.ts, packages/cli/src/reporters/__tests__/fixtures/browser-check-result.ts, packages/cli/src/reporters/__tests__/util.spec.ts, packages/cli/src/reporters/util.ts
Logs scheduling errors to the logs.
Example:
```
Running 1 checks in eu-west-1.
✖ Test API check (0ms)
──Scheduling Error────────
Your setup script timed out after 23010 milliseconds
src/__checks__/api-3.check.ts
✖ Test API check (0ms)
```
> Resolves #617
=> feat: log scheduling errors

examples/advanced-project/src/__checks__/home.check.ts
Fix the sentence:
> We explicitly define the Browser check here, instead of using ~generating~ a default based on a .spec.js file. 
Let me know if `generating` is the intended word.
=> fix: remove typo from `home.check.ts` description [sc-00]

.github/dependabot.yml
The dependabot github action has started failing, but it's not clear what triggered this. To resolve this, we can set the required `directory` property ([docs here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directory)).
=> fix: correctly configure dependabot directory

packages/cli/src/constructs/check.ts
Dont create alert subscriptions if `testOnly=true`
> Resolves #655
=> fix: dont create alert subscriptions when testOnly is true [gh-655]

packages/cli/src/commands/login.ts
Old URL was leading to the general Settings page. When clicking straight on `API keys` there (which is your mental mode since you came from `npx checkly login -h` telling you to go there finding API keys) then you get a deprecation warning that keys are based on users now. This is a fix to lead the user straight to the correct page.
=> login.ts: Fix help URL to API keys

packages/cli/src/commands/test.ts, packages/cli/src/reporters/__tests__/github-md-builder.spec.ts, packages/cli/src/reporters/__tests__/helpers.ts, packages/cli/src/reporters/abstract-list.ts, packages/cli/src/reporters/ci.ts, packages/cli/src/reporters/dot.ts, packages/cli/src/reporters/github.ts, packages/cli/src/reporters/list.ts, packages/cli/src/reporters/reporter.ts, packages/cli/src/services/abstract-check-runner.ts, packages/cli/src/services/test-runner.ts
The reporters are currently quite coupled to `checkly test` and will be tricky to work with for `checkly trigger`. This PR refactors the reporters to prepare for the `checkly trigger` command (https://github.com/checkly/checkly-cli/pull/609).
In particular:
1. All of the `Reporters` currently take the list of checks that will be run in the constructor. With `checkly trigger`, though, we won't know in advance which checks will actually be run (since the backend applies tag filters). This PR makes the reporters accept a list of checks that will be run in `onBegin` instead. Unfortunately, this means that we sometimes …
=> refactor: prepare reporters for checkly trigger command [sc-14206]

package-lock.json, packages/cli/e2e/__tests__/fixtures/check-parse-error/main.check.js, packages/cli/e2e/__tests__/fixtures/deploy-project/api.check.ts, packages/cli/e2e/__tests__/fixtures/test-duplicated-groups/group1.check.ts, packages/cli/e2e/__tests__/fixtures/test-duplicated-groups/group2.check.ts, packages/cli/e2e/__tests__/fixtures/test-only-project/checks.check.ts, packages/cli/e2e/__tests__/fixtures/test-project/checkly.config.ts, packages/cli/e2e/__tests__/fixtures/test-project/checkly.staging.config.ts, packages/cli/e2e/__tests__/fixtures/test-project/src/__checks__/group.check.ts, packages/cli/e2e/__tests__/fixtures/test-project/src/__checks__/secret.check.ts, packages/cli/e2e/__tests__/fixtures/test-project/src/alert-channels.ts, packages/cli/e2e/__tests__/fixtures/test-project/src/services/api/api.check.ts, packages/cli/e2e/__tests__/fixtures/test-project/src/services/api/typo.checkz.ts, packages/cli/package.json, packages/cli/src/commands/login.ts, packages/cli/src/services/__tests__/fixtures/configs/checkly.config.ts, packages/cli/src/services/__tests__/fixtures/configs/good-config.ts, packages/cli/src/services/check-parser/errors.ts
Relates to #566
We now control the `checkly` NPM package. This PR updates the CLI to be published their, instead of to `@checkly/cli`. Since the `checkly` package was previously used, we need to start by releasing version `4.0.0`.
In follow up PR's, I'll migrate the `@checkly/create-cli` package, the templates, and the README's. I first want to make sure that we can publish to `checkly`, though.
=> feat: change CLI package name

packages/cli/src/commands/test.ts, packages/cli/src/commands/trigger.ts, packages/cli/src/reporters/abstract-list.ts, packages/cli/src/reporters/github.ts, packages/cli/src/rest/test-sessions.ts, packages/cli/src/services/trigger-runner.ts, packages/cli/src/services/util.ts
This PR introduces a new command for running checks, `npx checkly trigger`.  Unlike `npx checkly test`, this lets you run checks that are stored on your Checkly account and not necessarily managed with MaC. It's possible to specify checks to run using tags: `npx checkly trigger -t target-tag`. For the most part, `npx checkly trigger` aims to be as similar as possible to `npx checkly test`.
```
$ npx checkly trigger --help
Trigger checks on Checkly
USAGE
$ checkly trigger [--private-location <value> | -l <value>] [-t <value>] [-c <value>] [--timeout <value>] [-v] [-r list|dot|ci|github] [-e <value> | --env-file …
```
=> feat: introduce checkly trigger command [sc-14206]

packages/create-cli/package.json
Publishing the `create-cli` package to NPM is currently broken due to `npx oclif manifest` failing during `prepack`: https://github.com/checkly/checkly-cli/actions/runs/4830121579.
From what I can see, this manifest step isn't actually necessary, though. The simplest way to fix this seems to be just removing this step. Since no customers are currently using the package with the new name, it should be safe to publish to NPM to try this.
=> fix: don't run oclif manifest for create-cli package

packages/cli/package.json, packages/cli/src/services/config.ts
> Relates to #566
We currently use [conf](https://www.npmjs.com/package/conf) for persisting credentials.  Conf persists credentials using a filename containing the package name. On MacOS, CLI credentials were persisted in `~/Library/Preferences/@checkly/cli`.
With https://github.com/checkly/checkly-cli/pull/665, we changed the package name to `checkly` and so the CLI now reads credentials from  `~/Library/Preferences/checkly`. This means that users migrating to the new CLI version need to recreate credentials and log in to Checkly!
To avoid this inconvenience and make the upgrade process smoother, we can simply …
=> fix: continue reading config for @checkly/cli

examples/boilerplate-project/checkly.config.ts
I missed removing a reference to `@checkly/cli` in https://github.com/checkly/checkly-cli/pull/668.
=> fix: remove another reference to @checkly/cli

examples/advanced-project/checkly.config.ts, examples/boilerplate-project/checkly.config.ts, package-lock.json, packages/cli/package.json, packages/cli/src/services/__tests__/project-parser.spec.ts, packages/cli/src/services/project-parser.ts
Updates the default runtime ID from `2022.10` to the latest runtime, `2023.02`. Tested that the examples still pass via `checkly test`.
=> feat: update default runtime IDs to 2023.02

packages/cli/e2e/__tests__/test.spec.ts, packages/cli/src/commands/test.ts, packages/cli/src/reporters/abstract-list.ts, packages/cli/src/reporters/ci.ts, packages/cli/src/reporters/dot.ts, packages/cli/src/reporters/github.ts, packages/cli/src/reporters/list.ts, packages/cli/src/reporters/reporter.ts
> Resolves #677
There's been a regression in `checkly test --list` (for more info, see the linked issue). This regression was introduced in https://github.com/checkly/checkly-cli/pull/662, where we required the list of checks to be passed to the reporter in `reporter.onBegin()` rather than in the constructor. Since `onBegin()` wasn't called for `checkly test --list`, the reporter wasn't properly initialized and there would be an error.
This PR resolves the issue by removing `reporter.onBeginStatic()`, which is the reporter-specific implementation for `checkly test --list`. `onBeginStatic()` was nice since it let …
=> fix: print checks for 'checkly test --list'

examples/advanced-project/src/services/docs/__checks__/docs-search.spec.ts
Currently the `docs-search.spec.ts` advanced example is failing. This is likely due to recent updates in the docs pages. This PR updates the test so that it's passing.
Shout-out to @modern-sapien for finding the issue and giving the fix.
=> fix(examples): update docs-search.spec.ts to match docs updates

package-lock.json, packages/cli/e2e/__tests__/env/env.add.spec.ts, packages/cli/e2e/__tests__/env/env.ls.spec.ts, packages/cli/e2e/__tests__/env/env.pull.spec.ts, packages/cli/e2e/__tests__/env/env.rm.spec.ts, packages/cli/e2e/__tests__/env/env.upate.spec.ts, packages/cli/package.json
The e2e tests for `checkly env` modify the account environment variables on the e2e test Checkly account. When there are multiple e2e tests ongoing in parallel, they can then interfere with each other and cause failures. For example, one test instance could delete the environment variable in it's cleanup right after it's added in the setup of the other test instance.
Running the e2e tests in parallel locally, this does end up causing failures. Looking at our history of flaky GitHub actions, though, this only caused a few flaky runs. Still, we should fix the issue.
This PR fixes the issue by creating a unique …
=> chore: handle concurrent e2e test runs for env tests

packages/cli/src/constructs/api-check.ts
=> fix: Call NOT_CONTANS in notContains method

packages/create-cli/src/utils/package.ts
For some reason `npm create checkly` doesn't detect `package.json` even if exists. Couldn't reproduce it in local mode, but this fix aims to solve it by having the full path of the file.
=> fix: detect if package.json exists [sc-15315]

packages/cli/e2e/__tests__/fixtures/deploy-project/defaults.ts, packages/cli/e2e/__tests__/fixtures/deploy-project/homepage.test.ts, packages/cli/e2e/__tests__/fixtures/test-project/src/__checks__/homepage.test.ts, packages/cli/e2e/__tests__/fixtures/test-project/src/defaults.ts
The recent changes to checklyhq.com have broken the end to end tests. Since we now use Danube in the examples, this PR fixes the issue by also using Danube in the e2e tests.
=> fix: update e2e tests to use Danube

packages/cli/src/reporters/__tests__/__snapshots__/util.spec.ts.snap, packages/cli/src/reporters/util.ts
> Resolves after release #697 
The linked issue reports `checkly trigger` causing an out of bounds error. This appears to happen in a CI environment:
```
RangeError: Invalid count value: -4
at String.repeat (<anonymous>)
at formatSectionTitle (/home/circleci/.npm/_npx/a66ee913fe899ce0/node_modules/checkly/src/reporters/util.ts:234:39)
...
```
This is caused by the terminal width being 0 in some CI environments (https://github.com/aws/aws-cdk/issues/2253).
When we format the section title, we then get a negative number and cause this out of bounds error:
https://github.com/checkly/checkly-cli/blob/e1b75b6a0f7d93ecc0a4fe …
=> fix: handle edge case when formatting reporter titles

packages/cli/e2e/__tests__/test.spec.ts, packages/cli/src/commands/test.ts, packages/cli/src/services/abstract-check-runner.ts
There is currently an issue with timeout support for `checkly test` and `checkly trigger`. This can be reproduced by running with `--timeout 0`:
```
$ npx checkly test --timeout 1
Parsing your project... done
Running 2 checks in eu-west-1.
__checks__/api.check.ts
- Fetch Book List
__checks__/homepage.spec.ts
- homepage.spec.ts
2 pending, 2 total
/Users/clample/projects/checkly-cli/packages/cli/src/commands/test.ts:211
reporters.forEach(r => r.onCheckEnd(checkRunId, {
^
TypeError: check.getSourceFile is not a function
at /Users/clample/projects/checkly-cli/packages/cli/src/commands/test.ts:214:27
at Array.forEach …
```
=> fix: ensure check run timeouts give clear error message

packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/top-level-await.js, packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/top-level-await.ts, packages/cli/src/services/check-parser/__tests__/check-parser.spec.ts, packages/cli/src/services/check-parser/parser.ts
Checks created in Checkly via the UI already support top-level `await`. For example, the following check runs successfully when created from the UI:
```
const sleep = ms => new Promise(r => setTimeout(r, ms));
await sleep(10000);
```
The CLI currently fails to parse checks with top-level `await`, though. It fails with the following error:
```
Encountered an error parsing check files for /Users/clample/projects/checkly-cli/packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/top-level-await.js.
The following NPM dependencies were used, but aren't supported in the runtimes.
For more information, see …
```
=> feat: support top level await in browser check scripts

packages/cli/src/commands/test.ts
Add the `--test-session-name` as a `test` command argument. It follows the same pattern using for the 
`trigger` command: it allows the user to override the `projectName` specified in the Checkly config file when the `--record` flag is activated.
We should deploy https://github.com/checkly/checkly-backend/pull/4197 first to override the `projectName` even if the project was already deployed/stored in the database.
> Resolves #704
=> feat: add --test-session-name arg to test command [gh-704]

packages/cli/src/constructs/browser-check.ts, packages/cli/src/constructs/check-group.ts, packages/cli/src/services/__tests__/project-parser-fixtures/empty-script-project/src/empty-envvar.check.js, packages/cli/src/services/__tests__/project-parser-fixtures/typescript-project/ts-test.check.ts, packages/cli/src/services/__tests__/project-parser.spec.ts
The PR adds a check for browser-check script payloads and check-group environment variable values during the project parsing. If there is an empty string, it throws a clear error message indicating the `logicalId` and/or environment variable.
=> feat: enhance empty script or env var value error [gh-714]

packages/cli/e2e/__tests__/help.spec.ts, packages/cli/package.json, packages/cli/src/commands/baseCommand.ts, packages/cli/src/commands/deploy.ts, packages/cli/src/commands/test.ts, packages/cli/src/commands/trigger.ts, packages/cli/src/help/help-extension.ts
Modify the `--help` information format, showing all commands treating the ones under topics as root commands. Commands are sorted by `CORE` and `ADDITIONAL` (default) categories.
Commands can be configured marked as `CORE COMMANDS` setting the `static coreCommand` property to `true`.
> Resolves #723
=> chore: show help info with sorted commands [gh-723]

packages/cli/e2e/__tests__/deploy.spec.ts, packages/cli/e2e/__tests__/fixtures/test-only-project/checkly.config.ts, packages/cli/e2e/__tests__/fixtures/test-only-project/checks.check.ts, packages/cli/e2e/__tests__/test.spec.ts, packages/cli/src/commands/deploy.ts, packages/cli/src/constructs/project.ts
Currently checks with `testOnly=true` aren't displayed at all in the deployment summary of `npx checkly deploy --preview` or `npx checkly deploy --output`. To give more info to users, this PR adds a "Skip" section to the deployment summary containing the `testOnly` checks.
There's an edge case where a check was deployed, then in a subsequent deployment the check is marked as `testOnly=true`. In this case, the check should be considered deleted rather than skipped, since it will be removed from Checkly. I added handling for this edge case and an integration test.
Choosing a color is tricky. Depending on the theme, it …
=> feat: display testOnly checks in deployment summary

packages/cli/src/services/__tests__/config.spec.ts, packages/cli/src/services/config.ts
Currently the CLI tries to create a config file even if `CHECKLY_ACCOUNT_ID` and `CHECKLY_API_KEY` are passed. In some environments (f.ex AWS Lambda), this can then trigger an error. This PR makes the creation of config files lazy. The config file should only be created if `CHECKLY_ACCOUNT_ID` or `CHECKLY_API_KEY` are missing, or for the `checkly switch` and `checkly login` commands.
The issue can be reproduced on Mac OS by deleting `~/Library/Preferences/@checkly/cli` and making `~/Library/Preferences/@checkly` read-only. `CHECKLY_ACCOUNT_ID=<someId> CHECKLY_API_KEY=<apiKey> npx checkly deploy` then fails with:
``` …
```
=> fix: lazily initialize config file

packages/cli/src/services/abstract-check-runner.ts
With the current canary release from `main`, test runs with `checkly test` always takes 20 seconds. This occurs even when the checks are shown as finished after only several seconds. This can be reproduced with `time checkly test` on the boilerplate example. 
This issue is because we aren't closing the timeout for `MAX_SCHEDULING_DELAY_EXCEEDED`, so the node process hangs until after it runs (in 20 seconds). This issue doesn't affect any public releases since it was merged after v4.0.8.
This PR fixes the issue by closing the timeout after all of the check runs have been scheduled. The code is similar to what we …
=> fix: properly close scheduling timer to avoid checkly test hanging

.github/workflows/release.yml, .github/workflows/test.yml, package.json, packages/cli/package.json, packages/create-cli/package.json
After adding the linting for the monorepo, the `npm ci` must be executed for the complete monorepo including both packages. The `release.yml` workflow is updated to install all dependencies.
The PR adds the `npm run prepack` command before running `tests` jobs. Apparaently, this fixes issues when running tests where the `package.json` version was already modified, and no `package-lock.json` is updated in the new PR.
=> fix: gh actions release build job

package-lock.json, packages/cli/package.json, packages/create-cli/package.json
I created a separate PR for the @types/node update. It seems to be fine and all the tests are passing. For some reason the original Dependabot PR is just missing the secrets (see screenshot) so all requests fail with HTTP 401 Unauthorized. I did not bother looking into why. 
Example CI run I took the screenshot from: https://github.com/checkly/checkly-cli/actions/runs/5451590463/jobs/9918010210?pr=783
=> chore(deps-dev): Bump @types/node from 18.11.18 to 20.3.3 

packages/cli/src/constructs/phone-call-alert-channel.ts, packages/cli/src/constructs/sms-alert-channel.ts
Adding optional `name` support to SMS &  Phone call constructs
=> feat: sms & phone call alert channels optional name support [sc-00]

packages/cli/e2e/__tests__/fixtures/esm-module/checkly.config.ts, packages/cli/e2e/__tests__/fixtures/esm-module/checks.check.ts, packages/cli/e2e/__tests__/fixtures/esm-module/package.json, packages/cli/e2e/__tests__/test.spec.ts, packages/cli/src/services/util.ts
> Resolves #768
Currently the CLI is unable to support TypeScript `checkly.config.ts` and `**.check.ts` files in projects that are configured as ECMAScript Module projects. This can be reproduced by setting `"type": "module"` in `package.json` for the boilerplate project:
```
$ npx checkly deploy
Parsing your project... !
Error: Error loading file /Users/clample/projects/test/amber-snake/checkly.config.ts
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/clample/projects/test/amber-snake/checkly.config.ts
require() of ES modules is not supported.
require() of …
```
=>  fix: override ts-node module behaviour [gh-768] 

packages/cli/src/constructs/slack-alert-channel.ts, packages/cli/src/constructs/webhook-alert-channel.ts
Allow strings to be passed as urls. This is to handle handlebar templates in the string urls
=> fix: allow strings to be passed as urls [gh-0]

packages/cli/package.json
The e2e tests make use of `CHECKLY_BASE_URL` to make API requests for cleanup. In particular, `deploy.spec.ts` is using `CHECKLY_BASE_URL` via `config`. Without setting this env var, `deploy.spec.ts` fails when running `npm run test:e2e:local`.
To avoid us needing to set this manually when running the e2e tests locally, this PR adds it to the `test:e2e:local` command.
=> chore: set CHECKLY_BASE_URL for local e2e tests

packages/cli/src/constructs/api-check.ts
`AssertionBuilder.responseTme()` had a typo. This PR fixes the typo in a backwards compatible way. To avoid breaking existing projects, this PR leaves `responseTme()` in the codebase. This PR also marks the method as deprecated. This puts it at the bottom of the Visual Studio code suggestions.
=> fix: use correct spelling for AssertionBuilder.responseTime()

packages/cli/e2e/__tests__/fixtures/deploy-project/browser.check.ts, packages/cli/src/constructs/browser-check.ts
This PR adds `sslCheckDomain` into `BrowserCheck` construct.
> Depends on https://github.com/checkly/checkly-backend/pull/4591
=> chore: add sslCheckDomain property [gh-0]

packages/cli/src/commands/deploy.ts, packages/cli/src/constructs/project.ts, packages/cli/src/rest/api.ts, packages/cli/src/rest/heartbeat-checks.ts, packages/cli/src/rest/projects.ts
When creating or updating heartbeat checks from `npx checkly deploy`, we want to print in the console the ping URL of each heartbeat check.
iTerm2:
Terminal with default theme:
Note: needs [deploy response adjustment PR](https://github.com/checkly/checkly-backend/pull/4593) on the BE when testing.
=> feat(heartbeat): print `pingUrl` in the console after deploy for heartbeat checks [sc-17085]

packages/cli/src/services/config.ts
On Mac, I receive the following error when running the CLI with `CHECKLY_ENV=local`:
```
Error: Encountered an error connecting to Checkly. Please check that the internet connection is working. connect ECONNREFUSED ::1:3000
```
The CLI tries to connect to the IPv6 loopback address. The local setup isn't bound to the IPv6 interface, though, so this fails. To fix the issue, we can make sure that the CLI always uses the IPv4 address.
=> fix: use ipv4 for local setup

packages/cli/e2e/__tests__/test.spec.ts, packages/cli/src/reporters/github.ts
This PR adds test-session link (if the `--record` flag is set) when using `--reporter=github`.
> Resolves #822
=> chore: add test-session link on github reporter [gh-822]

packages/cli/src/constructs/heartbeat-check.ts
`addSubscription` is needed to register all the alert channels connected to a heartbeat
=> fix(heartbeats): addSubscriptions to alert channels [sc-17522]

packages/cli/src/rest/api.ts
Adds a header with the CI name if available. This helps us determine which CI systems are mostly used so we can have better docs and integration support.
=> chore: adds CI name as header to API

packages/cli/src/constructs/check-group.ts, packages/cli/src/constructs/check.ts
The `doubleCheck` property for checks and groups is being replaced with `retryStrategy`, which allows for more flexibility in specifying how to retry failed check runs. This PR marks the `doubleCheck` property as deprecated so that users can begin migrating.
I also verified that `doubleCheck` isn't used in any of the examples.
=> feat: deprecate doubleCheck property

examples/advanced-project-js/checkly.config.js, examples/advanced-project-js/src/__checks__/website-group.check.js, examples/advanced-project/checkly.config.ts, examples/advanced-project/src/__checks__/website-group.check.ts
This PR adds examples of the new `retryStrategy` property to the advanced examples. Since this isn't supported on deprecated plans, deprecated users will get errors when running the advanced example.
=> feat: add retryStrategy to the advanced examples

packages/cli/src/constructs/retry-strategy.ts
This PR updates the `RetryStrategyBuilder` to handle no `options` argument being passed. Since we already have default values for all options, the `options` argument isn't required. To improve the UX, we can update the types accordingly. Now it's possible to simply do `RetryStrategyBuilder.fixedStrategy()`.
=> feat: allow no options for RetryStrategyBuilder

packages/cli/src/constructs/frequency.ts
When setting the check frequency, we don't allow `EVERY_3M`, instead we should allow `EVERY_3H` which is currently missing.
=> fix(frequency): fix typo to handle `EVERY_3H` frequency [sc-00]

package-lock.json, packages/cli/package.json
Upgrade typescript parser to the latest version, 6.x, to support typescript 5.2 and above
Resolves #848 with the next release
=> chore: upgrade typescript eslint parser to support typescript 5 [gh-848]

packages/cli/src/commands/deploy.ts, packages/cli/src/commands/test.ts, packages/cli/src/constructs/__tests__/browser-check.spec.ts, packages/cli/src/constructs/browser-check.ts, packages/cli/src/rest/api.ts, packages/cli/src/rest/checkly-storage.ts, packages/cli/src/services/abstract-check-runner.ts, packages/cli/src/services/snapshot-service.ts, packages/cli/src/services/test-runner.ts, packages/cli/src/services/util.ts
This PR adds initial support for PWT snapshot testing in the CLI . `npx checkly test --update-snapshots` updates any snapshots using the actual result of this test run. `npx checkly deploy` can then be used to actually push the snapshots: it updates the snapshots used by the check on Checkly.
TODO:
One limitation in the current implementation is that we push the files to storage with every `npx checkly deploy`. We could probably improve this by adding some change detection using hashing. Such an implementation would be more complicated, though, so maybe we save it for later.
Integration tests are failing since the …
=> feat: add alpha support for PWT snapshot testing

package-lock.json, packages/cli/package.json, packages/create-cli/package.json
This bumps `axios` to `1.6.2` to resolve [CVE-2023-45857](https://github.com/advisories/GHSA-wf5p-g6vw-rhxx)
=> chore(deps): bump axios to 1.6.2

.github/workflows/release.yml, CONTRIBUTING.md
We've run into different issues with `create-checkly` fetching the examples (https://github.com/checkly/checkly-cli/issues/844). To avoid any mistakes during CLI releases, this PR adds validation to make sure that versions are formatted like `4.1.0` (and not `v4.1.0`). Even if adding a `v` prefix doesn't cause issues, I think that having complete consistency between releases is going to be safer.
Tested on a personal repo:
https://github.com/clample/commerce/actions
=> chore: validate tag format during release

packages/cli/src/constructs/browser-check.ts, packages/cli/src/constructs/browser-defaults.ts, packages/cli/src/services/checkly-config-loader.ts
Add support for playwright config on browser check
Used [RFC](https://github.com/checkly/checkly-cli/issues/806) as reference for parameters supported
=> feat: add support for playwright config on browser checks

packages/cli/src/constructs/check-group.ts
Send runtimeId with the group construct
Resolves #909
=> fix: send runtimeId to the BE [gh-909]

packages/cli/src/commands/deploy.ts, packages/cli/src/constructs/check-group.ts, packages/cli/src/services/__tests__/project-parser-fixtures/multiple-glob-patterns-project/__checks1__/__nested-checks__/nested.spec.js, packages/cli/src/services/__tests__/project-parser-fixtures/multiple-glob-patterns-project/__checks1__/__nested-checks__/test.check.js, packages/cli/src/services/__tests__/project-parser-fixtures/multiple-glob-patterns-project/__checks1__/check1.spec.js, packages/cli/src/services/__tests__/project-parser-fixtures/multiple-glob-patterns-project/__checks1__/test.check.js, packages/cli/src/services/__tests__/project-parser-fixtures/multiple-glob-patterns-project/__checks2__/check2.spec.js, packages/cli/src/services/__tests__/project-parser-fixtures/multiple-glob-patterns-project/__checks2__/test.check.js, packages/cli/src/services/__tests__/project-parser.spec.ts, packages/cli/src/services/checkly-config-loader.ts, packages/cli/src/services/project-parser.ts
- allows `string[]` for all glob patterns.
- adds tests to showcase that all heavy lifting (deduplications etc.) is done by the underlying glob library
For instance, you can just add arrays to the `checkly.config.ts` i.e.
```
checkMatch: ['**/__checks__/**/*.check.ts', '**/more-checks/**/*.check.ts'],
browserChecks: {
testMatch: ['**/__checks__/**/*.spec.ts', 'other-tests/**/*.spec.ts'],
```
Even with nested folders, the glob library will return a set of paths and checks that matches the expectations, e.g. no duplicates in overlapping glob definitions.
> Resolves #[911]
=> feat: support arrays of glob patterns

packages/cli/src/reporters/ci.ts, packages/cli/src/reporters/dot.ts
Not all the reporters were printing the test session url
Resolves [#918](https://github.com/checkly/checkly-cli/issues/918)
=> fix: print session url on all reporters

packages/cli/e2e/__tests__/help.spec.ts, packages/cli/src/commands/sync-playwright.ts
`npx checkly help` now shows `sync-playwright` command
=> feat: make sync-playwright command visible

packages/cli/e2e/__tests__/sync-playwright.spec.ts, packages/cli/src/commands/sync-playwright.ts, packages/cli/src/constructs/browser-check.ts, packages/cli/src/constructs/multi-step-check.ts, packages/cli/src/constructs/playwright-config.ts, packages/cli/src/playwright/playwright-config-template.ts, packages/cli/src/services/checkly-config-loader.ts, packages/create-cli/src/actions/playwright.ts
1. Move the playwright configuration on our checkly configuration at a check level
2. Made it so that multistep checks can also use the playwright config
=> feat: move playwright config at check level

examples/advanced-project-js/checkly.config.js, examples/advanced-project-js/src/__checks__/homepage.spec.js, examples/advanced-project-js/src/__checks__/login.spec.js, examples/advanced-project-js/src/defaults.js, examples/advanced-project/checkly.config.ts, examples/advanced-project/src/__checks__/homepage.spec.ts, examples/advanced-project/src/__checks__/login.spec.ts, examples/advanced-project/src/defaults.ts, examples/boilerplate-project-js/checkly.config.js, examples/boilerplate-project/checkly.config.ts
- adds `playwrightConfig` section to examples.
- adds actual usage of that section to advanced example and removes the `defaults` file that actually served this function.
=> docs: adds playwrightConfig options to examples [sc-00]

.github/workflows/release.yml, CONTRIBUTING.md
The release.yml job already pushes pre-releases to NPM so that we can do some extra testing. The problem is that if we find an issue, it's hard to reset everything: NPM doesn't allow us to unpublish the prerelease and we can't overwrite it either.
This PR adds the commit SHA to the prerelease version. If we detect an issue in the prerelease phase, we can delete the Github release, fix the issue, and trigger another release.
This PR will also automatically push the `v` tag with the release, since that has been causing issues for old `create-checkly` versions.
=> chore: allow testing multiple prereleases

packages/cli/src/services/test-runner.ts
We are using `error` key  [on the api ](https://github.com/checkly/checkly-backend/blob/main/api/src/modules/public-api/test-sessions/PublicTestSessionsController.js#L141)for populating the error message when triggering test on the CLI
=> fix: error messages are passed using error key

packages/cli/src/constructs/alert-escalation-policy.ts
Add new alert settings options:
```
alertEscalationPolicy: {
parallelRunFailureThreshold: {
enabled: true,
percentage: 100,
}
}
```
=> feat: add alertSettings.parallelRunFailureTreshold to CLI [sc-19200]

packages/cli/src/constructs/check-group.ts, packages/cli/src/constructs/check.ts, packages/cli/src/constructs/retry-strategy.ts
Resolves #943 
Currently it's not straightforward to disable smart retries. Setting `retryStrategy: null` for a check gives a type error when using TypeScript (`type 'null' is not assignable to type 'RetryStrategy | undefined'`). When using JS, the [backend Joi default of `doubleCheck: true`](https://github.com/checkly/checkly-backend/blob/cd20f50db575b121052eb016d57b894f9a67f77b/api/src/modules/public-api/checkly-cli-schema.js#L317-L320) shows in the UI as a linear retry strategy. Currently to disable all retries you need to set both `retryStrategy: null` and `doubleCheck: false`.
This PR makes it simpler to disable …
=> fix: allow disabling smart retries [gh-943]

examples/advanced-project-js/README.md, examples/advanced-project/README.md, examples/boilerplate-project-js/README.md, examples/boilerplate-project/README.md
Replace `npx check deploy` with `npx checkly deploy` in all examples' READMEs.
=> fix typo in example repos readmes

packages/cli/src/constructs/api-check.ts
Add IPv4 or IPv6 option to api checks
=> feat: allow users to choose ipv4 or ipv6 for api checks [sc-0]

packages/cli/src/commands/trigger.ts, packages/cli/src/services/abstract-check-runner.ts
Currently both `npx checkly test` and `npx checkly trigger` support a `--timeout` flag. This is a fallback timeout to make sure that if the Checkly backend doesn't respond with a check result for some reason, the user's CI doesn't become stuck indefinitely.
When it was originally added, there were few users of the CLI and checks ran on AWS Lambda which was able to run all checks concurrently. Now, users have very large test suites which can take longer, and have sometimes bumped into the default 300 second timeout. We'll also be adding test retries which will further increase the time tests take.
This PR simply bumps …
=> feat: increase test session timeout

packages/cli/src/commands/trigger.ts
When running `npx checkly trigger`, the summary always lists the checks as "scheduling" even when they're completed. The root cause is that the CLI isn't calling the reporter on the `CHECK_INPROGRESS` event to mark the check is started. This is already correctly set for the `npx checkly test` command:
https://github.com/checkly/checkly-cli/blob/440b8513ae260f60864a8600613d4e99a7a0a200/packages/cli/src/commands/test.ts#L251-L253
=> fix: correctly track check state for checkly-trigger

packages/cli/e2e/__tests__/deploy.spec.ts, packages/cli/e2e/__tests__/fixtures/retry-project/checkly.config.ts, packages/cli/e2e/__tests__/fixtures/retry-project/src/__checks__/group.check.ts, packages/cli/e2e/__tests__/test.spec.ts, packages/cli/e2e/run-checkly.ts, packages/cli/src/commands/test.ts, packages/cli/src/commands/trigger.ts, packages/cli/src/reporters/__tests__/__snapshots__/json-builder.spec.ts.snap, packages/cli/src/reporters/__tests__/fixtures/api-check-result.ts, packages/cli/src/reporters/__tests__/fixtures/browser-check-result.ts, packages/cli/src/reporters/__tests__/helpers.ts, packages/cli/src/reporters/abstract-list.ts, packages/cli/src/reporters/ci.ts, packages/cli/src/reporters/dot.ts, packages/cli/src/reporters/github.ts, packages/cli/src/reporters/json.ts, packages/cli/src/reporters/list.ts, packages/cli/src/reporters/reporter.ts, packages/cli/src/reporters/util.ts, packages/cli/src/rest/test-sessions.ts, packages/cli/src/services/abstract-check-runner.ts, packages/cli/src/services/checkly-config-loader.ts, packages/cli/src/services/test-runner.ts, packages/cli/src/services/trigger-runner.ts
This PR adds support for retrying failed tests with `npx checkly test` and `npx checkly trigger`. Users can configure retries by either passing the `--retries=<numRetries>` flag or by setting `retries` in their Checkly config file.
Previously the CLI tracked the state of a check run by using the `CheckRunId`. When MQTT/WebSocket updates were received, the CLI would look up which check it was for based on the `CheckRunId`. 
Since we now have retries, the `CheckRunId` can be different with each retry of a check. In order to track the check state, this PR switches the CLI to use `SequenceId`. This is stable across all …
=> feat: add support for test retries [sc-20570]

examples/advanced-project-js/checkly.config.js, examples/advanced-project/checkly.config.ts, examples/boilerplate-project-js/checkly.config.js, examples/boilerplate-project/checkly.config.ts
Test retry support was added in https://github.com/checkly/checkly-cli/pull/952. Retries can be set using the `--retries` flag or adding `retries` in the `checkly.config.ts`, and the `--retries` flag takes precedence. This PR adds `retries` to the example projects.
=> feat: add test retries to examples

packages/cli/src/commands/env/add.ts, packages/cli/src/commands/env/pull.ts, packages/cli/src/commands/env/update.ts, packages/cli/src/constructs/key-value-pair.ts, packages/cli/src/rest/environment-variables.ts
> [!IMPORTANT]
> Important note: this feature is not available yet, if you have any questions feel free to reach out to our customer support
=> feat: add environment secrets support [sc-21028]

package-lock.json, packages/cli/package.json, packages/cli/src/services/abstract-check-runner.ts, packages/cli/src/services/socket-client.ts
It seems that the async-mqtt wrapper has not been updated for a few years and our usage does not require it. It's more future proof to just use mqtt directly.
Relevant MqttClient calls have been updated to Async variants.
While technically mqtt was added to package.json, it was already used indirectly via async-mqtt.
=> chore: update mqtt to latest 5.x and remove unneeded async-mqtt wrapper

packages/cli/src/services/socket-client.ts
MQTT client reconnections were disabled for seemingly no reason. Combined with the fact that the SocketClient's various error and disconnection events were completely ignored, a random disconnection before the expected final message was received would almost certainly cause the CLI to essentially hang, doing nothing until the failsafe timeout (currently 10m) hit.
There is an additional edge case which is not covered by this change. Even now that reconnections are enabled, in the unlucky case that the final message is distributed when our client is not connected (i.e. in the process waiting to reconnect, or actively reconnecting), then we'll still miss it and hang the same way. To reduce the odds of this edge condition happening, the reconnect wait timeout was reduced to 100ms from the …
=> fix: allow mqtt client to reconnect if it gets disconnected

package-lock.json, packages/cli/package.json, packages/cli/src/rest/projects.ts, packages/cli/src/rest/test-sessions.ts, packages/cli/src/rest/util.ts
When you deploy or test a project, a potentially very large JSON payload is sent to the API server. In large projects, the time to upload the payload can be quite significant (depending on connection speed). This PR introduces gzip compression to payloads sent to relevant endpoints, which should make the payload easier to upload.
Additionally, those large payloads were stringified fully in memory, causing unnecessarily high memory usage. This PR changes the payload to be stringified and streamed with json-stream-stringify instead, which should decrease memory usage. This change only applies to requests that are now also getting compressed.
I hereby confirm that I followed the code guidelines found at [engineering guidelines](https://www.notion.so/checkly/Engineering-Guidelines-a3a165a203a0 …
=> feat: compress large JSON requests [sc-22310]

packages/cli/src/constructs/playwright-config.ts
* Adds the TypeScript type for `HttpProxy` that complies with Playwright documentation [here](https://playwright.dev/docs/network#http-proxy).
=> feat: added TS types for http proxy - `[sc-22386]`

packages/cli/e2e/__tests__/fixtures/test-project/src/alert-channels.ts, packages/cli/e2e/__tests__/fixtures/test-project/src/services/api/api.check.ts, packages/cli/src/constructs/webhook-alert-channel.ts
=> feat: add webhook secret support for webhook alert channels [sc-22462]

packages/cli/src/commands/deploy.ts, packages/cli/src/commands/test.ts, packages/cli/src/constructs/api-check.ts, packages/cli/src/constructs/browser-check.ts, packages/cli/src/constructs/multi-step-check.ts, packages/cli/src/constructs/project.ts, packages/cli/src/services/check-parser/__tests__/check-parser.spec.ts, packages/cli/src/services/check-parser/parser.ts, packages/cli/src/services/project-parser.ts
Introduces a new option called `--[no-]verify-runtime-dependencies` for the `test` and `deploy` commands, which is `true` by default and matches current behavior. Should the user decide that they know the available dependencies better than we do, they can run the commands with the `--no-verify-runtime-dependencies` flag set, or they can use the equivalent `CHECKLY_VERIFY_RUNTIME_DEPENDENCIES=0` environment variable.
Specifically, this feature makes it possible to use custom dependencies that have been added to a customized private location runtime (contact your Account Executive to learn how).
> Resolves …
=> feat: optionally bypass runtime dependency checks [sc-22475]

packages/cli/e2e/__tests__/trigger.spec.ts, packages/cli/src/commands/trigger.ts, packages/cli/src/services/checkly-config-loader.ts
This will be useful for us to assert results from this in CI and such but I would understand if you'd prefer to not take it. Also happy to change the name, etc.
=> feat: allow configuring the CLI to error on no matching tests

packages/cli/src/commands/deploy.ts, packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/common-esm-example/dep5.mjs, packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/common-esm-example/dep6.mjs, packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/common-esm-example/entrypoint.mjs, packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/common-esm-example/unreachable.mjs, packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/esmodules-example/dep5.js, packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/esmodules-example/dep6.js, packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/esmodules-example/entrypoint.js, packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/esmodules-example/unreachable.js, packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/simple-example/unreachable.js, packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/typescript-example/dep5.ts, packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/typescript-example/dep6.ts, packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/typescript-example/entrypoint.ts, packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/typescript-example/unreachable.ts, packages/cli/src/services/check-parser/__tests__/check-parser.spec.ts, packages/cli/src/services/check-parser/parser.ts
This PR makes the project parser compatible with wildcard exports such as `export * from './file'`. Previously, only named exports such as `export { Thing } from './file'` were supported. The end result was that the file being referred to in the export would not be added to the dependency tree.
=> feat: support wildcard exports when parsing dependency tree [sc-22632]

packages/cli/src/constructs/api-check.ts, packages/cli/src/constructs/browser-check.ts, packages/cli/src/constructs/check-group.ts, packages/cli/src/constructs/dashboard.ts, packages/cli/src/constructs/email-alert-channel.ts, packages/cli/src/constructs/heartbeat-check.ts, packages/cli/src/constructs/maintenance-window.ts, packages/cli/src/constructs/multi-step-check.ts, packages/cli/src/constructs/opsgenie-alert-channel.ts, packages/cli/src/constructs/pagerduty-alert-channel.ts, packages/cli/src/constructs/private-location.ts, packages/cli/src/constructs/slack-alert-channel.ts, packages/cli/src/constructs/sms-alert-channel.ts, packages/cli/src/constructs/webhook-alert-channel.ts
Some @link JS docs were pointing to an old URL which triggered a redirect, losing the anchor.
=> fix: updates wrong links to correct url. [sc-00]

packages/cli/e2e/__tests__/switch.spec.ts, packages/cli/src/commands/deploy.ts, packages/cli/src/commands/test.ts, packages/cli/src/constructs/__tests__/api-check.spec.ts, packages/cli/src/constructs/__tests__/browser-check.spec.ts, packages/cli/src/constructs/__tests__/multi-step-check.spec.ts, packages/cli/src/constructs/api-check.ts, packages/cli/src/constructs/browser-check.ts, packages/cli/src/constructs/multi-step-check.ts, packages/cli/src/constructs/project.ts, packages/cli/src/rest/accounts.ts, packages/cli/src/services/__tests__/project-parser.spec.ts, packages/cli/src/services/project-parser.ts
The CLI had a hardcoded default runtime value of `2024.02`, which became the effective value if no runtime was set at check or project level. Now, the account's default runtime is used instead. Additionally, if the account's default runtime is used, then we leave `runtimeId` undefined when synthesizing resources. This allows the user to have their checks always use the current account default runtime if they wish. If they do not wish to have such behavior, they should set a default runtime at project level as usual.
Technically speaking this is a potentially breaking change if a user has something other than `2024.02` set as their default account runtime, and have never set a runtime at project or check level. When they next deploy their checks (or run `checkly test`), a different runtime …
=> feat: check constructs against account default runtime if not given [sc-22843]

packages/cli/e2e/__tests__/deploy.spec.ts, packages/cli/e2e/__tests__/fixtures/deploy-project/snapshot-test.test.ts, packages/cli/e2e/run-checkly.ts, packages/cli/src/commands/baseCommand.ts, packages/cli/src/commands/deploy.ts, packages/cli/src/commands/sync-playwright.ts, packages/cli/src/commands/test.ts
Also makes it so that fancy output (or some of it anyway) is now disabled for E2E tests because it's annoying and hid this particular issue.
=> fix: fix broken and flaky e2e test

packages/cli/src/services/check-parser/__tests__/check-parser-fixtures/builtin-with-node-prefix/entrypoint.ts, packages/cli/src/services/check-parser/__tests__/check-parser.spec.ts, packages/cli/src/services/check-parser/package-files/paths.ts, packages/cli/src/services/check-parser/package-files/resolver.ts, packages/cli/src/services/check-parser/parser.ts
This PR makes both `import 'node:path'` and `import 'path'` equivalent.
Also fixes a typo in the supported dependency list: `'readline '` had a trailing space.
=> feat: support `node:` prefix for built-in modules [sc-22633]

packages/cli/e2e/__tests__/fixtures/tcp-check-failures/checkly.config.ts, packages/cli/e2e/__tests__/fixtures/tcp-check-failures/tcp.check.ts, packages/cli/src/reporters/util.ts
This PR adds reporter support for TCP check assertion and connection errors.
I added a new fixture folder with TCP checks that at least currently are able to trigger various error scenarios. However, I am undecided as to whether such checks are stable enough to use in e2e checks, so the fixtures are currently unused.
=> feat: add assertion and connection error reporters to TCP checks [sc-23082]

packages/cli/src/reporters/__tests__/__snapshots__/util.spec.ts.snap, packages/cli/src/reporters/__tests__/util.spec.ts, packages/cli/src/reporters/abstract-list.ts, packages/cli/src/reporters/ci.ts, packages/cli/src/reporters/dot.ts, packages/cli/src/reporters/github.ts, packages/cli/src/reporters/json.ts, packages/cli/src/reporters/list.ts, packages/cli/src/reporters/util.ts
This PR adds the "degraded" state to all relevant points, mostly in the reporters. Previously all interactions with "degraded" states (e.g. `test` and `trigger`) all reported a "degraded" check as "passed / successful". It reports the "degraded" state with a ⚠️ icon and yellow text. 
- adds to ci, dot, list and github reporters.
- adds to abtract list and summary.
- adds a small helper to not have double ternary statements everywhere.
- adds tests.
=> feat: adds degraded state to reporters [sc-00]

README.md, examples/advanced-project-js/README.md, examples/advanced-project/README.md, examples/boilerplate-project-js/README.md, examples/boilerplate-project/README.md, packages/cli/e2e/__tests__/help.spec.ts, packages/cli/package.json, packages/cli/src/commands/trigger.ts, packages/cli/src/help/examples.ts, packages/cli/src/messages/common-messages.ts, packages/cli/src/reporters/__tests__/__snapshots__/github-md-builder.spec.ts.snap, packages/cli/src/reporters/abstract-list.ts, packages/cli/src/reporters/ci.ts, packages/cli/src/reporters/github.ts, packages/cli/src/reporters/list.ts, packages/create-cli/e2e/__tests__/bootstrap.spec.ts, packages/create-cli/src/utils/messages.ts
-  adds a hint on relevant reporters to use `--record` if the user did not use it when running `test` or `trigger`
- adds a copy & pastable hint on updating the CLI when there is a new version.
- small wording updates to other parts.
Resolves #1018 
Resolves #973
=> feat: update inline hints and tips

package-lock.json, packages/cli/package.json, packages/create-cli/package.json
The reason for this change is that new versions of many of our dependencies now require Node 18 or later, meaning we cannot update them without breaking compatibility. Bumping our Node version in a major release makes that possible again.
This is a breaking change (despite probably no one using Node 16 anymore), so a new major version is required.
=> chore!: update node engine requirement to >=18 [sc-23291]

packages/cli/src/services/check-parser/package-files/extension.ts
It seems that some users are using declaration files as shared header files and there is nothing else to resolve. During normal transpilation, any such imports would get removed and the declaration file would not be part of the dist bundle. Since we transpile on the runner, it would be nice to have the file available there even though it's not technically even required. More importantly however this change makes the parser not complain about missing dependencies if it encounters imports that can only be resolved to a declaration file.
=> feat: resolve declaration files (e.g. `.d.ts`) as a last resort [sc-23313]

packages/cli/src/constructs/api-check.ts
This PR adds support for the `assertions` property of `apiCheckDefaults` which is already output by the UI's code generator. It can be used with `AssertionBuilder`.
I verified locally that the property is now getting sent to the backend and gets reflected correctly in the UI.
=> feat: add assertions to CheckGroup's API check defaults [sc-23331]

packages/cli/src/commands/test.ts
This is the intended behavior, but an oversight in the code effectively disabled it.
> Resolves #1044
=> fix: the `test` command's `--tags` option now also matches `CheckGroup`s [sc-23699]

packages/cli/src/services/check-parser/__tests__/parse-files.spec.ts, packages/cli/src/services/check-parser/parser.ts, packages/cli/src/services/project-parser.ts, packages/cli/src/services/util.ts
Parse now has a new method that allows the user to get all files and dependencies by providing a list of directories, files or globs
This is the first PR for multiple file/type input for code bundling.
Following PRs 
1. allow to ignore directories/globs/files
2. Add snapshots
This method is not currently being used in any place of the code, it's sitting idle until we implement PWT native
=> feat: allow parsing multiple input types

.github/workflows/test.yml, examples/advanced-project/package.json, examples/boilerplate-project/package.json, package-lock.json, packages/cli/package.json, packages/cli/src/playwright/playwright-config-loader.ts, packages/cli/src/services/__tests__/checkly-config-loader.spec.ts, packages/cli/src/services/checkly-config-loader.ts, packages/cli/src/services/project-parser.ts, packages/cli/src/services/util.ts, packages/create-cli/e2e/__tests__/fixtures/initiated-project/package.json, packages/create-cli/e2e/__tests__/fixtures/playwright-project/package.json, packages/create-cli/package.json, packages/create-cli/src/actions/dependencies.ts, packages/create-cli/src/actions/playwright.ts, packages/create-cli/src/utils/__tests__/fixtures/checkly-project/package.json, packages/create-cli/src/utils/directory.ts, packages/create-cli/src/utils/fileloader.ts
This PR merges #1041.
Temporarily disables testing on Windows due to (presumably) ts-jest and jiti fighting over the module cache. A different test setup is needed to make this work.
=> feat: full ESM config support using Jiti (build #1041)

packages/cli/src/services/util.ts, packages/create-cli/src/utils/fileloader.ts
If a user already had jiti 1.x installed, or managed to install it in some way without violating `peerDependencies`, we'd be unable to use it because we expected jiti 2.x.
=> fix: avoid breakage if user has jiti 1.x installed [sc-24059]

packages/cli/package.json, packages/cli/src/commands/sync-playwright.ts, packages/cli/src/constructs/project.ts, packages/cli/src/loader/index.ts, packages/cli/src/loader/jiti.ts, packages/cli/src/loader/loader.ts, packages/cli/src/loader/match.ts, packages/cli/src/loader/mixed.ts, packages/cli/src/loader/native.ts, packages/cli/src/loader/ts-node.ts, packages/cli/src/playwright/playwright-config-loader.ts, packages/cli/src/services/checkly-config-loader.ts, packages/cli/src/services/project-parser.ts, packages/cli/src/services/util.ts
Files are now loaded with a more intelligent loader that's able to utilize several different options. Additionally it is able to simply utilize the native loader in runtimes that support TypeScript natively.
The main benefits of improving the loader are:
1. The ability to skip `jiti` and `ts-node` if the runtime already supports TypeScript, which avoids a whole bunch of potential conflicts and should be way faster too. Currently, it will detect Deno and Bun.
2. The ability to collect exports of check files, which can be used for more intelligent code generation for the import feature.
3. The ability for the user to define their own loader if they like, and for us to easily define more loaders.
=> feat: more intelligent file loader [sc-24135]

packages/cli/src/commands/import/plan.ts
Due to an oversight, `Program` was getting reused between retried import runs which resulted in duplicate code.
Some slight refactoring should be done in the future to clean it up a little (mostly to avoid having to create a program for interactive filters which only need the `.describe()` from the codegen) but this change will do for now.
=> fix: avoid duplicate resources when retrying an import [sc-24150]

packages/cli/src/commands/import/plan.ts, packages/cli/src/constructs/check-codegen.ts, packages/cli/src/constructs/check-group-codegen.ts, packages/cli/src/constructs/email-alert-channel-codegen.ts, packages/cli/src/constructs/incidentio-alert-channel-codegen.ts, packages/cli/src/constructs/internal/codegen/context.ts, packages/cli/src/constructs/msteams-alert-channel-codegen.ts, packages/cli/src/constructs/opsgenie-alert-channel-codegen.ts, packages/cli/src/constructs/pagerduty-alert-channel-codegen.ts, packages/cli/src/constructs/phone-call-alert-channel-codegen.ts, packages/cli/src/constructs/private-location-codegen.ts, packages/cli/src/constructs/project.ts, packages/cli/src/constructs/slack-alert-channel-codegen.ts, packages/cli/src/constructs/sms-alert-channel-codegen.ts, packages/cli/src/constructs/status-page-codegen.ts, packages/cli/src/constructs/status-page-service-codegen.ts, packages/cli/src/constructs/telegram-alert-channel-codegen.ts, packages/cli/src/constructs/webhook-alert-channel-codegen.ts, packages/cli/src/rest/projects.ts, packages/cli/src/sourcegen/program.ts
If you import resources that refer to other resources that were already part of your project, previously we'd create `<Resource>.fromId()` references for them. With this change, we'll instead try to find a matching exported construct in the codebase which we can then import in the generated file.
=> feat: use existing variables in code generated for import [sc-24139]

packages/cli/src/constructs/email-alert-channel-codegen.ts, packages/cli/src/constructs/incidentio-alert-channel-codegen.ts, packages/cli/src/constructs/msteams-alert-channel-codegen.ts, packages/cli/src/constructs/opsgenie-alert-channel-codegen.ts, packages/cli/src/constructs/pagerduty-alert-channel-codegen.ts, packages/cli/src/constructs/phone-call-alert-channel-codegen.ts, packages/cli/src/constructs/slack-alert-channel-codegen.ts, packages/cli/src/constructs/sms-alert-channel-codegen.ts, packages/cli/src/constructs/telegram-alert-channel-codegen.ts, packages/cli/src/constructs/webhook-alert-channel-codegen.ts
Earlier, all alert channels of the same type were bundled into the same file. Unfortunately when you did a per-resource import of the same type later, it would clear everything else in the file and only include the newly generated construct.
Now, each alert channels is in a separate file.
=> fix: create a separate file for each imported alert channel [sc-24153]

packages/cli/src/constructs/project.ts
Currently it's possible to mistakenly use a value that is not a string if you are not using TypeScript, or your editor is not capable of showing compile errors. Since `jiti` is quite forgiving, it will let the user use an invalid value.
=> chore: validate that logicalId is always a string [sc-24161]

packages/cli/src/loader/mixed.ts
This would cause the loader to fail if Jiti could not be found, or an earlier version of Jiti was used.
The reason why I did not spot this earlier is that during manual testing, I used a symlink to the checkly package, which led to Node finding the appropriate version of `jiti` in the checkly-cli repo (or in other words, from the node_modules folder relative to the actual file behind the symlink). So it seemed to work, but in fact did not. I have now correctly verified both the issue and the fix with `npm pack` and using the generated archive instead.
=> fix: the new FileLoader did not implement fallback correctly [sc-24179]

packages/create-cli/e2e/__tests__/bootstrap.spec.ts, packages/create-cli/e2e/run-create-cli.ts, packages/create-cli/src/commands/bootstrap.ts
The bootstrap tests are taking ages on Windows and eventually fail, sometimes due to what seems like an internal vitest timeout (probably, our `spawnSync` calls prevented internal state updates). Since this worked before, perhaps it's just due to GH Windows runners being slow right now, but it's resulting in a lot of friction in PRs. Make bootstrap tests async and increase timeout of long tests to hopefully avoid this issue entirely.
=> fix(tests): fix CI flakiness/slowness on Windows [sc-24403]

packages/cli/package.json, packages/cli/src/commands/baseCommand.ts, packages/cli/src/services/check-parser/package-files/package-json-file.ts, packages/create-cli/package.json
Adds a warning if the user is running a Node version that isn't supported. The supported version is retrieved from package.json.
The create-cli is not updated for now as it is in need of other changes as well.
The minimum version is updated to `^18.19.0 || >=20.5.0` which matches the value `execa` uses. Right now it's mainly execa that's causing incompatibility issues.
=> feat: output a warning if user is using an incompatible version of Node [sc-24193]

packages/cli/src/loader/jiti.ts, packages/cli/src/loader/ts-node.ts, packages/create-cli/src/loader/index.ts, packages/create-cli/src/loader/jiti.ts, packages/create-cli/src/loader/loader.ts, packages/create-cli/src/loader/match.ts, packages/create-cli/src/loader/mixed.ts, packages/create-cli/src/loader/native.ts, packages/create-cli/src/loader/ts-node.ts, packages/create-cli/src/utils/fileloader.ts, packages/create-cli/tsconfig.json
The old file loader has issues that the new loader resolves, plus we'd ideally use the same loader everywhere anyway.
We do not currently have a good way to share common code between the workspace packages. For now, just copy the files until we have time for a real solution.
It would have been too much trouble to bring over Bun and Deno detection, so they were left out for now.
=> feat: use the new FileLoader in create-cli [sc-24412]

package-lock.json, packages/create-cli/package.json
The only supported usage of the create-cli is via the `npm create` command. When used, the package gets installed to a global location and any dependencies it tries to load are resolved from that global location. Therefore even if the user adds jiti by themselves, it's not going to be effective because the create-cli will not see it.
It makes sense to just include jiti outright in create-cli because it's intended to be purely a CLI and not a library.
=> feat: include jiti directly in create-cli because it's not a library [sc-24412]

packages/cli/e2e/__tests__/trigger.spec.ts, packages/cli/src/commands/trigger.ts, packages/cli/src/services/checkly-config-codegen.ts, packages/cli/src/services/checkly-config-loader.ts
Until `--fail-on-no-matching` was added some time ago, the `trigger` command would return a 0 exit code if no checks matched, which was likely a mistake in the original implementation. The `--fail-on-no-matching`  flag made it possible to enable more sensible behavior without breaking backwards compatibility. With the v6 major release we are now making it the default.
The `failOnNoMatching` option in Checkly config has been removed because realistically the only reason why you'd want to set the flag is to enable it. Since it's now enabled by default, and the option only applied to the trigger command anyway, there is no reason to keep the option anymore.
=> feat: make --fail-on-no-matching true by default for the trigger command [sc-24516]

packages/cli/src/constructs/__tests__/browser-check.spec.ts, packages/cli/src/constructs/__tests__/multi-step-check.spec.ts, packages/cli/src/constructs/browser-check.ts, packages/cli/src/constructs/multi-step-check.ts, packages/cli/src/services/checkly-config-codegen.ts, packages/cli/src/services/checkly-config-loader.ts
The issue was caused by the introduction of typed defaults in version 6.1.0. However, it turns out that the original type (which was used more of as a hint) had never included `playwrightConfig`, but it had still been working because all properties were overwritten blindly regardless of whether they were present in the type or not.
This change makes BrowserChecks and MultiStepChecks use the appropriate default playwrightConfig again. Tests were added to make sure it won't break again.
=> fix: default playwrightConfig was not being set for Browser/MultiStep checks [sc-24851]

packages/cli/src/commands/baseCommand.ts, packages/cli/src/commands/import/plan.ts, packages/cli/src/services/check-parser/package-files/package-json-file.ts
This PR changes the hardcoded default to dynamically load the CLI's own version instead. Ensures that we don't forget to bump it.
=> feat: use CLI's own version when adding checkly to package.json on import [sc-24879]

packages/cli/e2e/__tests__/deploy.spec.ts, packages/cli/e2e/__tests__/fixtures/deploy-project/api.check.ts, packages/cli/src/constructs/__tests__/api-check.spec.ts, packages/cli/src/constructs/retry-strategy-codegen.ts, packages/cli/src/constructs/retry-strategy.ts
This PR introduces support for limiting retry strategies to network errors.
To opt a retry strategy into this behavior, specify the `onlyOn` property as part of your RetryStrategy:
```typescriot
RetryStrategyBuilder.fixedStrategy({
onlyOn: 'NETWORK_ERROR',
})
```
We do have the option to extend the `RetryStrategyCondition` type (the type of the value of `onlyOn`) later if more types or combinations become available.
=> feat: retry strategies can now be limited to network errors [sc-24520]

packages/cli/src/constructs/retry-strategy.ts
Unfortunately the `onlyOn` property was not applied correctly when used with the `RetryStrategyBuilder`. It only worked if used manually without the builder.
We should add tests for the builder.
=> fix: the RetryStrategyBuilder now applies the onlyOn condition properly [sc-24520]

packages/cli/src/constructs/api-check.ts, packages/cli/src/constructs/check.ts, packages/cli/src/constructs/retry-strategy.ts, packages/cli/src/constructs/url-monitor.ts
Using `RetryStrategy.onlyOn` with checks/monitors other than `ApiCheck`/`UrlMonitor` will now produce the following validation error:
```
✖ [TcpMonitor:tcpsample-1] Invalid property value
The value provided for property "retryStrategy" is not valid.
Reason: Using "NETWORK_ERROR" with "onlyOn" is only supported in the
ApiCheck and UrlMonitor constructs.
✖ [BrowserCheck:browsersample-1] Invalid property value
The value provided for property "retryStrategy" is not valid.
Reason: Using "NETWORK_ERROR" with "onlyOn" is only supported in the
ApiCheck and UrlMonitor constructs.
```
Also, using any other value for `onlyOn` will produce the following error (in addition to TypeScript showing an error):
```
✖ [BrowserCheck:browsersample-1] Invalid property value
The value provided for property …
```
=> feat: validate that onlyOn: NETWORK_ERROR is only used with ApiCheck/UrlMonitor [sc-24520]

packages/cli/e2e/__tests__/env/env.add.spec.ts, packages/cli/e2e/__tests__/env/env.rm.spec.ts, packages/cli/e2e/__tests__/env/env.upate.spec.ts, packages/cli/src/commands/deploy.ts, packages/cli/src/commands/destroy.ts, packages/cli/src/commands/env/add.ts, packages/cli/src/commands/env/rm.ts, packages/cli/src/commands/env/update.ts, packages/cli/src/commands/import/plan.ts, packages/cli/src/commands/trigger.ts, packages/cli/src/helpers/command-style.ts, packages/cli/src/rest/api.ts, packages/cli/src/rest/environment-variables.ts, packages/cli/src/rest/errors.ts, packages/cli/src/rest/projects.ts, packages/cli/src/rest/test-sessions.ts, packages/cli/src/services/test-runner.ts, packages/cli/src/services/trigger-runner.ts
This PR adds better handling for API errors. Most errors are now intercepted by a global handler which attempts to make the API responses a bit more digestible, and when necessary, API endpoints can provide more specialized errors too.
Slightly alters the output of some commands. I have plans to improve the overall CLI output in a separate PR.
=> feat: add better handling for API errors [sc-25199]

packages/cli/src/services/check-parser/package-files/package-manager.ts, packages/cli/src/services/check-parser/package-files/resolver.ts, packages/cli/src/services/check-parser/package-files/walk.ts, packages/cli/src/services/util.ts
PW native checks were looking for a lockfile in the same directory where the PW config is located, which doesn't quite work as expected when using workspaces. Now parent folders are also used to search for a lockfile.
Similarly, package manager detection did not consider parent folders when attempting to detect the presence of a lockfile. Now they are checked.
Note that this functionality is not tested very well, so changes need to be made carefully.
=> fix: search for lockfile in parent directiories
